// SPDX-License-Identifier: Apache-2.0

// This file serves as the entry point for the LUP Migrations Plugin.
// It exports the migration manager for use by dbtool.
//
// Build Configuration:
// Set LUPMIGRATION_SQL_DIR in CMake to point to the directory containing
// LUP SQL migration files (init_m_*.sql, upd_m_*.sql). The build system
// will automatically run lup2dbtool to generate C++ migrations.
//
// Example:
//   cmake -DLUPMIGRATION_SQL_DIR=/path/to/lup-sql ..
//
// The generated migrations are compiled as a separate source file and
// linked into this plugin. Use TransitionGlue::Initialize() to migrate
// from LASTRADA_PROPERTIES to schema_migrations before running migrations
// for the first time on an existing database.

#include <Lightweight/SqlMigration.hpp>
#include <Lightweight/SqlQuery/MigrationPlan.hpp>

#include <set>
#include <string>

// Note: Generated migrations (GeneratedMigrations.cpp) are compiled separately
// and linked into this plugin via CMake. The migrations auto-register with
// the MigrationManager through static initialization.

namespace
{

/// @brief Upper bound (exclusive) of the LUP-sourced migration timestamp range.
///
/// Every migration generated by `lup2dbtool` from legacy LUP SQL falls below this
/// timestamp. The `9999_99_99` sentinel placeholder lives at `20'000'099'999'999`,
/// safely above any real release. Anything at or beyond this bound is, by
/// definition, *not* a LUP-sourced migration and gets the strict modern policy.
constexpr uint64_t kLupLegacyTimestampUpperBound = 20'000'070'000'000ULL;

/// @brief Returns the compat flags that apply to a single LUP migration.
///
/// Pure function: no side effects, no I/O, no state. Installed once as the
/// `MigrationManager`'s compat policy at plugin load time.
///
/// **Every migration this plugin contributes is legacy by definition** — they are
/// all sourced from LUpd SQL files via `lup2dbtool`, and LUpd silently
/// client-side-truncated string values that exceeded the destination column's
/// declared width. We replicate that behaviour (with audit logging) for the full
/// plugin range so post-6.0.0 LUP migrations carrying over-long strings still
/// apply against MSSQL strict NCHAR sizing — same way they always did under LUpd.
///
/// The earlier design called for a hard cutoff at the 6.0.0 release on the
/// assumption that post-6.0.0 SQL would be cleaned up before generation; in
/// practice the post-6.0.0 LUP files still contain over-long inserts (e.g.
/// `upd_m_6_01_12.sql` writes a 61-char value into `TEXTBAUSTEINGRUPPEN.NAME`,
/// which is `NCHAR(60)`). Treating the whole `lup_*.cpp` body as legacy keeps
/// `dbtool migrate` working end-to-end without modifying source SQL.
std::set<std::string> LupCompatPolicy(Lightweight::SqlMigration::MigrationBase const& m)
{
    if (m.GetTimestamp().value < kLupLegacyTimestampUpperBound)
        return { std::string(Lightweight::CompatFlagLupTruncateName) };
    return {};
}

/// @brief RAII-less registrar that installs `LupCompatPolicy` on the singleton
/// `MigrationManager` at shared-library load time. Lives in an anonymous namespace
/// so the symbol stays plugin-local.
struct PolicyInstaller
{
    PolicyInstaller()
    {
        Lightweight::SqlMigration::MigrationManager::GetInstance().SetCompatPolicy(&LupCompatPolicy);
    }
};

[[maybe_unused]] PolicyInstaller const kInstallPolicy {};

} // namespace

// Export the migration manager for dbtool plugin loading
LIGHTWEIGHT_MIGRATION_PLUGIN()
