var annotated_dup =
[
    [ "Lightweight", null, [
      [ "SqlBackup", null, [
        [ "ChunkReader", "d2/d99/structLightweight_1_1SqlBackup_1_1ChunkReader.html", "d2/d99/structLightweight_1_1SqlBackup_1_1ChunkReader" ],
        [ "ChunkWriter", "dd/d06/structLightweight_1_1SqlBackup_1_1ChunkWriter.html", "dd/d06/structLightweight_1_1SqlBackup_1_1ChunkWriter" ],
        [ "ColumnBatch", "d1/d6f/structLightweight_1_1SqlBackup_1_1ColumnBatch.html", "d1/d6f/structLightweight_1_1SqlBackup_1_1ColumnBatch" ],
        [ "Progress", "d5/db5/structLightweight_1_1SqlBackup_1_1Progress.html", "d5/db5/structLightweight_1_1SqlBackup_1_1Progress" ],
        [ "ProgressManager", "d2/d4a/structLightweight_1_1SqlBackup_1_1ProgressManager.html", "d2/d4a/structLightweight_1_1SqlBackup_1_1ProgressManager" ],
        [ "TableFilter", "d9/dfd/classLightweight_1_1SqlBackup_1_1TableFilter.html", "d9/dfd/classLightweight_1_1SqlBackup_1_1TableFilter" ],
        [ "TableInfo", "d9/dfa/structLightweight_1_1SqlBackup_1_1TableInfo.html", "d9/dfa/structLightweight_1_1SqlBackup_1_1TableInfo" ]
      ] ],
      [ "SqlMigration", null, [
        [ "Migration", "d4/d32/classLightweight_1_1SqlMigration_1_1Migration.html", "d4/d32/classLightweight_1_1SqlMigration_1_1Migration" ],
        [ "MigrationBase", "de/dfc/classLightweight_1_1SqlMigration_1_1MigrationBase.html", "de/dfc/classLightweight_1_1SqlMigration_1_1MigrationBase" ],
        [ "MigrationManager", "d4/d5c/classLightweight_1_1SqlMigration_1_1MigrationManager.html", "d4/d5c/classLightweight_1_1SqlMigration_1_1MigrationManager" ],
        [ "MigrationTimestamp", "d3/d3b/structLightweight_1_1SqlMigration_1_1MigrationTimestamp.html", null ]
      ] ],
      [ "SqlSchema", null, [
        [ "Column", "d2/db8/structLightweight_1_1SqlSchema_1_1Column.html", null ],
        [ "EventHandler", "df/da2/classLightweight_1_1SqlSchema_1_1EventHandler.html", "df/da2/classLightweight_1_1SqlSchema_1_1EventHandler" ],
        [ "Table", "d3/dda/structLightweight_1_1SqlSchema_1_1Table.html", "d3/dda/structLightweight_1_1SqlSchema_1_1Table" ]
      ] ],
      [ "Tools", null, [
        [ "PluginLoader", "d3/df0/classLightweight_1_1Tools_1_1PluginLoader.html", null ]
      ] ],
      [ "BelongsTo", "d0/df7/classLightweight_1_1BelongsTo.html", "d0/df7/classLightweight_1_1BelongsTo" ],
      [ "DataMapper", "de/d61/classLightweight_1_1DataMapper.html", "de/d61/classLightweight_1_1DataMapper" ],
      [ "DataMapperOptions", "d3/db2/structLightweight_1_1DataMapperOptions.html", null ],
      [ "Field", "d2/dd0/structLightweight_1_1Field.html", "d2/dd0/structLightweight_1_1Field" ],
      [ "HasMany", "da/df4/classLightweight_1_1HasMany.html", "da/df4/classLightweight_1_1HasMany" ],
      [ "HasManyThrough", "de/d73/classLightweight_1_1HasManyThrough.html", "de/d73/classLightweight_1_1HasManyThrough" ],
      [ "HasOneThrough", "df/d63/classLightweight_1_1HasOneThrough.html", "df/d63/classLightweight_1_1HasOneThrough" ],
      [ "SqlAllFieldsQueryBuilder", "d8/d5d/classLightweight_1_1SqlAllFieldsQueryBuilder.html", null ],
      [ "SqlAlterTablePlan", "dd/d75/structLightweight_1_1SqlAlterTablePlan.html", "dd/d75/structLightweight_1_1SqlAlterTablePlan" ],
      [ "SqlAlterTableQueryBuilder", "d8/dad/classLightweight_1_1SqlAlterTableQueryBuilder.html", "d8/dad/classLightweight_1_1SqlAlterTableQueryBuilder" ],
      [ "SqlBinary", "db/db6/classLightweight_1_1SqlBinary.html", null ],
      [ "SqlColumnDeclaration", "dd/d71/structLightweight_1_1SqlColumnDeclaration.html", "dd/d71/structLightweight_1_1SqlColumnDeclaration" ],
      [ "SqlCompositeForeignKeyConstraint", "d3/d18/structLightweight_1_1SqlCompositeForeignKeyConstraint.html", "d3/d18/structLightweight_1_1SqlCompositeForeignKeyConstraint" ],
      [ "SqlConnection", "da/da8/classLightweight_1_1SqlConnection.html", "da/da8/classLightweight_1_1SqlConnection" ],
      [ "SqlConnectionDataSource", "d6/d8d/structLightweight_1_1SqlConnectionDataSource.html", null ],
      [ "SqlConnectionString", "de/d6a/structLightweight_1_1SqlConnectionString.html", null ],
      [ "SqlCoreDataMapperQueryBuilder", "da/d51/classLightweight_1_1SqlCoreDataMapperQueryBuilder.html", "da/d51/classLightweight_1_1SqlCoreDataMapperQueryBuilder" ],
      [ "SqlCreateTableQueryBuilder", "d4/de8/classLightweight_1_1SqlCreateTableQueryBuilder.html", "d4/de8/classLightweight_1_1SqlCreateTableQueryBuilder" ],
      [ "SqlDataBinderCallback", "d9/dbb/classLightweight_1_1SqlDataBinderCallback.html", "d9/dbb/classLightweight_1_1SqlDataBinderCallback" ],
      [ "SqlDate", "d9/de1/structLightweight_1_1SqlDate.html", "d9/de1/structLightweight_1_1SqlDate" ],
      [ "SqlDateTime", "d6/dfa/structLightweight_1_1SqlDateTime.html", "d6/dfa/structLightweight_1_1SqlDateTime" ],
      [ "SqlDeleteQueryBuilder", "d1/d57/classLightweight_1_1SqlDeleteQueryBuilder.html", null ],
      [ "SqlDropTablePlan", "dd/d47/structLightweight_1_1SqlDropTablePlan.html", "dd/d47/structLightweight_1_1SqlDropTablePlan" ],
      [ "SqlDynamicBinary", "d6/db6/classLightweight_1_1SqlDynamicBinary.html", "d6/db6/classLightweight_1_1SqlDynamicBinary" ],
      [ "SqlDynamicString", "d7/d9a/classLightweight_1_1SqlDynamicString.html", "d7/d9a/classLightweight_1_1SqlDynamicString" ],
      [ "SqlErrorInfo", "d8/d5b/structLightweight_1_1SqlErrorInfo.html", null ],
      [ "SqlFixedString", "de/dae/classLightweight_1_1SqlFixedString.html", "de/dae/classLightweight_1_1SqlFixedString" ],
      [ "SqlForeignKeyReferenceDefinition", "d5/d8f/structLightweight_1_1SqlForeignKeyReferenceDefinition.html", "d5/d8f/structLightweight_1_1SqlForeignKeyReferenceDefinition" ],
      [ "SqlGuid", "df/d7c/structLightweight_1_1SqlGuid.html", null ],
      [ "SqlInsertQueryBuilder", "de/dd9/classLightweight_1_1SqlInsertQueryBuilder.html", null ],
      [ "SqlLogger", "db/dfd/classLightweight_1_1SqlLogger.html", "db/dfd/classLightweight_1_1SqlLogger" ],
      [ "SqlMigrationPlan", "d3/ded/structLightweight_1_1SqlMigrationPlan.html", null ],
      [ "SqlMigrationQueryBuilder", "d8/d65/classLightweight_1_1SqlMigrationQueryBuilder.html", "d8/d65/classLightweight_1_1SqlMigrationQueryBuilder" ],
      [ "SqlNullType", "da/d96/structLightweight_1_1SqlNullType.html", null ],
      [ "SqlNumeric", "d6/d1b/structLightweight_1_1SqlNumeric.html", "d6/d1b/structLightweight_1_1SqlNumeric" ],
      [ "SqlQueryBuilder", "de/da0/classLightweight_1_1SqlQueryBuilder.html", "de/da0/classLightweight_1_1SqlQueryBuilder" ],
      [ "SqlQueryFormatter", "d8/df7/classLightweight_1_1SqlQueryFormatter.html", "d8/df7/classLightweight_1_1SqlQueryFormatter" ],
      [ "SqlRawColumn", "da/d7e/structLightweight_1_1SqlRawColumn.html", "da/d7e/structLightweight_1_1SqlRawColumn" ],
      [ "SqlRawColumnMetadata", "da/d07/structLightweight_1_1SqlRawColumnMetadata.html", "da/d07/structLightweight_1_1SqlRawColumnMetadata" ],
      [ "SqlRawSqlPlan", "dc/d47/structLightweight_1_1SqlRawSqlPlan.html", "dc/d47/structLightweight_1_1SqlRawSqlPlan" ],
      [ "SqlRealName", "d7/d13/structLightweight_1_1SqlRealName.html", null ],
      [ "SqlRequireLoadedError", "da/df2/classLightweight_1_1SqlRequireLoadedError.html", null ],
      [ "SqlResultCursor", "d8/d63/classLightweight_1_1SqlResultCursor.html", "d8/d63/classLightweight_1_1SqlResultCursor" ],
      [ "SqlRowIterator", "d2/d8e/classLightweight_1_1SqlRowIterator.html", null ],
      [ "SqlScopedTimeLogger", "dc/d6c/classLightweight_1_1SqlScopedTimeLogger.html", null ],
      [ "SqlScopedTraceLogger", "df/d9c/classLightweight_1_1SqlScopedTraceLogger.html", null ],
      [ "SqlSelectQueryBuilder", "de/d33/classLightweight_1_1SqlSelectQueryBuilder.html", "de/d33/classLightweight_1_1SqlSelectQueryBuilder" ],
      [ "SqlStatement", "db/dad/classLightweight_1_1SqlStatement.html", "db/dad/classLightweight_1_1SqlStatement" ],
      [ "SqlText", "de/dfe/structLightweight_1_1SqlText.html", null ],
      [ "SqlTime", "d7/d53/structLightweight_1_1SqlTime.html", null ],
      [ "SqlTransaction", "d0/ddc/classLightweight_1_1SqlTransaction.html", "d0/ddc/classLightweight_1_1SqlTransaction" ],
      [ "SqlTransactionException", "d5/d19/classLightweight_1_1SqlTransactionException.html", null ],
      [ "SqlVariant", "df/d3f/structLightweight_1_1SqlVariant.html", "df/d3f/structLightweight_1_1SqlVariant" ],
      [ "UniqueNameBuilder", "da/d15/classLightweight_1_1UniqueNameBuilder.html", "da/d15/classLightweight_1_1UniqueNameBuilder" ]
    ] ]
];