var annotated_dup =
[
    [ "Lightweight", null, [
      [ "SqlAlterTableCommands", null, [
        [ "AddColumnIfNotExists", "dc/dbd/structLightweight_1_1SqlAlterTableCommands_1_1AddColumnIfNotExists.html", "dc/dbd/structLightweight_1_1SqlAlterTableCommands_1_1AddColumnIfNotExists" ],
        [ "DropColumnIfExists", "d1/d55/structLightweight_1_1SqlAlterTableCommands_1_1DropColumnIfExists.html", "d1/d55/structLightweight_1_1SqlAlterTableCommands_1_1DropColumnIfExists" ],
        [ "DropIndexIfExists", "d9/dd1/structLightweight_1_1SqlAlterTableCommands_1_1DropIndexIfExists.html", "d9/dd1/structLightweight_1_1SqlAlterTableCommands_1_1DropIndexIfExists" ]
      ] ],
      [ "SqlBackup", null, [
        [ "BackupSettings", "d9/dd5/structLightweight_1_1SqlBackup_1_1BackupSettings.html", "d9/dd5/structLightweight_1_1SqlBackup_1_1BackupSettings" ],
        [ "ChunkReader", "d2/d99/structLightweight_1_1SqlBackup_1_1ChunkReader.html", "d2/d99/structLightweight_1_1SqlBackup_1_1ChunkReader" ],
        [ "ChunkWriter", "dd/d06/structLightweight_1_1SqlBackup_1_1ChunkWriter.html", "dd/d06/structLightweight_1_1SqlBackup_1_1ChunkWriter" ],
        [ "ColumnBatch", "d1/d6f/structLightweight_1_1SqlBackup_1_1ColumnBatch.html", "d1/d6f/structLightweight_1_1SqlBackup_1_1ColumnBatch" ],
        [ "ErrorTrackingProgressManager", "df/da5/classLightweight_1_1SqlBackup_1_1ErrorTrackingProgressManager.html", "df/da5/classLightweight_1_1SqlBackup_1_1ErrorTrackingProgressManager" ],
        [ "Progress", "d5/db5/structLightweight_1_1SqlBackup_1_1Progress.html", "d5/db5/structLightweight_1_1SqlBackup_1_1Progress" ],
        [ "ProgressManager", "d2/d4a/structLightweight_1_1SqlBackup_1_1ProgressManager.html", "d2/d4a/structLightweight_1_1SqlBackup_1_1ProgressManager" ],
        [ "RestoreSettings", "da/d0d/structLightweight_1_1SqlBackup_1_1RestoreSettings.html", "da/d0d/structLightweight_1_1SqlBackup_1_1RestoreSettings" ],
        [ "RetrySettings", "d4/d9f/structLightweight_1_1SqlBackup_1_1RetrySettings.html", "d4/d9f/structLightweight_1_1SqlBackup_1_1RetrySettings" ],
        [ "Sha256", "d2/d43/classLightweight_1_1SqlBackup_1_1Sha256.html", "d2/d43/classLightweight_1_1SqlBackup_1_1Sha256" ],
        [ "TableFilter", "d9/dfd/classLightweight_1_1SqlBackup_1_1TableFilter.html", "d9/dfd/classLightweight_1_1SqlBackup_1_1TableFilter" ],
        [ "TableInfo", "d9/dfa/structLightweight_1_1SqlBackup_1_1TableInfo.html", "d9/dfa/structLightweight_1_1SqlBackup_1_1TableInfo" ]
      ] ],
      [ "SqlMigration", null, [
        [ "ChecksumVerificationResult", "da/d49/structLightweight_1_1SqlMigration_1_1ChecksumVerificationResult.html", "da/d49/structLightweight_1_1SqlMigration_1_1ChecksumVerificationResult" ],
        [ "Migration", "d4/d32/classLightweight_1_1SqlMigration_1_1Migration.html", "d4/d32/classLightweight_1_1SqlMigration_1_1Migration" ],
        [ "MigrationBase", "de/dfc/classLightweight_1_1SqlMigration_1_1MigrationBase.html", "de/dfc/classLightweight_1_1SqlMigration_1_1MigrationBase" ],
        [ "MigrationLock", "d0/d8d/classLightweight_1_1SqlMigration_1_1MigrationLock.html", "d0/d8d/classLightweight_1_1SqlMigration_1_1MigrationLock" ],
        [ "MigrationManager", "d4/d5c/classLightweight_1_1SqlMigration_1_1MigrationManager.html", "d4/d5c/classLightweight_1_1SqlMigration_1_1MigrationManager" ],
        [ "MigrationStatus", "d8/d37/structLightweight_1_1SqlMigration_1_1MigrationStatus.html", "d8/d37/structLightweight_1_1SqlMigration_1_1MigrationStatus" ],
        [ "MigrationTimestamp", "d3/d3b/structLightweight_1_1SqlMigration_1_1MigrationTimestamp.html", "d3/d3b/structLightweight_1_1SqlMigration_1_1MigrationTimestamp" ],
        [ "RevertResult", "d1/de7/structLightweight_1_1SqlMigration_1_1RevertResult.html", "d1/de7/structLightweight_1_1SqlMigration_1_1RevertResult" ]
      ] ],
      [ "SqlSchema", null, [
        [ "Column", "d2/db8/structLightweight_1_1SqlSchema_1_1Column.html", "d2/db8/structLightweight_1_1SqlSchema_1_1Column" ],
        [ "EventHandler", "df/da2/classLightweight_1_1SqlSchema_1_1EventHandler.html", "df/da2/classLightweight_1_1SqlSchema_1_1EventHandler" ],
        [ "IndexDefinition", "d6/de6/structLightweight_1_1SqlSchema_1_1IndexDefinition.html", "d6/de6/structLightweight_1_1SqlSchema_1_1IndexDefinition" ],
        [ "Table", "d3/dda/structLightweight_1_1SqlSchema_1_1Table.html", "d3/dda/structLightweight_1_1SqlSchema_1_1Table" ]
      ] ],
      [ "Zip", null, [
        [ "EntryInfo", "d7/d09/structLightweight_1_1Zip_1_1EntryInfo.html", "d7/d09/structLightweight_1_1Zip_1_1EntryInfo" ],
        [ "ZipArchive", "d4/d8a/classLightweight_1_1Zip_1_1ZipArchive.html", "d4/d8a/classLightweight_1_1Zip_1_1ZipArchive" ],
        [ "ZipEntry", "d6/d46/classLightweight_1_1Zip_1_1ZipEntry.html", "d6/d46/classLightweight_1_1Zip_1_1ZipEntry" ],
        [ "ZipError", "da/dd4/structLightweight_1_1Zip_1_1ZipError.html", "da/dd4/structLightweight_1_1Zip_1_1ZipError" ]
      ] ],
      [ "AliasedTableName", "d1/d0e/structLightweight_1_1AliasedTableName.html", "d1/d0e/structLightweight_1_1AliasedTableName" ],
      [ "BelongsTo", "d0/df7/classLightweight_1_1BelongsTo.html", "d0/df7/classLightweight_1_1BelongsTo" ],
      [ "DataMapper", "de/d61/classLightweight_1_1DataMapper.html", "de/d61/classLightweight_1_1DataMapper" ],
      [ "DataMapperOptions", "d3/db2/structLightweight_1_1DataMapperOptions.html", "d3/db2/structLightweight_1_1DataMapperOptions" ],
      [ "Field", "d2/dd0/structLightweight_1_1Field.html", "d2/dd0/structLightweight_1_1Field" ],
      [ "HasMany", "da/df4/classLightweight_1_1HasMany.html", "da/df4/classLightweight_1_1HasMany" ],
      [ "HasManyThrough", "de/d73/classLightweight_1_1HasManyThrough.html", "de/d73/classLightweight_1_1HasManyThrough" ],
      [ "HasOneThrough", "df/d63/classLightweight_1_1HasOneThrough.html", "df/d63/classLightweight_1_1HasOneThrough" ],
      [ "Pool", "d3/d30/classLightweight_1_1Pool.html", "d3/d30/classLightweight_1_1Pool" ],
      [ "PoolConfig", "df/d1a/structLightweight_1_1PoolConfig.html", null ],
      [ "SqlAllFieldsQueryBuilder", "d8/d5d/classLightweight_1_1SqlAllFieldsQueryBuilder.html", null ],
      [ "SqlAlterTablePlan", "dd/d75/structLightweight_1_1SqlAlterTablePlan.html", "dd/d75/structLightweight_1_1SqlAlterTablePlan" ],
      [ "SqlAlterTableQueryBuilder", "d8/dad/classLightweight_1_1SqlAlterTableQueryBuilder.html", "d8/dad/classLightweight_1_1SqlAlterTableQueryBuilder" ],
      [ "SqlBinary", "db/db6/classLightweight_1_1SqlBinary.html", "db/db6/classLightweight_1_1SqlBinary" ],
      [ "SqlColumnDeclaration", "dd/d71/structLightweight_1_1SqlColumnDeclaration.html", "dd/d71/structLightweight_1_1SqlColumnDeclaration" ],
      [ "SqlCompositeForeignKeyConstraint", "d3/d18/structLightweight_1_1SqlCompositeForeignKeyConstraint.html", "d3/d18/structLightweight_1_1SqlCompositeForeignKeyConstraint" ],
      [ "SqlConnection", "da/da8/classLightweight_1_1SqlConnection.html", "da/da8/classLightweight_1_1SqlConnection" ],
      [ "SqlConnectionDataSource", "d6/d8d/structLightweight_1_1SqlConnectionDataSource.html", "d6/d8d/structLightweight_1_1SqlConnectionDataSource" ],
      [ "SqlConnectionString", "de/d6a/structLightweight_1_1SqlConnectionString.html", "de/d6a/structLightweight_1_1SqlConnectionString" ],
      [ "SqlCoreDataMapperQueryBuilder", "da/d51/classLightweight_1_1SqlCoreDataMapperQueryBuilder.html", "da/d51/classLightweight_1_1SqlCoreDataMapperQueryBuilder" ],
      [ "SqlCreateIndexPlan", "dd/d2b/structLightweight_1_1SqlCreateIndexPlan.html", "dd/d2b/structLightweight_1_1SqlCreateIndexPlan" ],
      [ "SqlCreateTableQueryBuilder", "d4/de8/classLightweight_1_1SqlCreateTableQueryBuilder.html", "d4/de8/classLightweight_1_1SqlCreateTableQueryBuilder" ],
      [ "SqlDataBinderCallback", "d9/dbb/classLightweight_1_1SqlDataBinderCallback.html", "d9/dbb/classLightweight_1_1SqlDataBinderCallback" ],
      [ "SqlDate", "d9/de1/structLightweight_1_1SqlDate.html", "d9/de1/structLightweight_1_1SqlDate" ],
      [ "SqlDateTime", "d6/dfa/structLightweight_1_1SqlDateTime.html", "d6/dfa/structLightweight_1_1SqlDateTime" ],
      [ "SqlDeleteDataPlan", "d2/d72/structLightweight_1_1SqlDeleteDataPlan.html", "d2/d72/structLightweight_1_1SqlDeleteDataPlan" ],
      [ "SqlDeleteQueryBuilder", "d1/d57/classLightweight_1_1SqlDeleteQueryBuilder.html", "d1/d57/classLightweight_1_1SqlDeleteQueryBuilder" ],
      [ "SqlDropTablePlan", "dd/d47/structLightweight_1_1SqlDropTablePlan.html", "dd/d47/structLightweight_1_1SqlDropTablePlan" ],
      [ "SqlDynamicBinary", "d6/db6/classLightweight_1_1SqlDynamicBinary.html", "d6/db6/classLightweight_1_1SqlDynamicBinary" ],
      [ "SqlDynamicString", "d7/d9a/classLightweight_1_1SqlDynamicString.html", "d7/d9a/classLightweight_1_1SqlDynamicString" ],
      [ "SqlErrorInfo", "d8/d5b/structLightweight_1_1SqlErrorInfo.html", "d8/d5b/structLightweight_1_1SqlErrorInfo" ],
      [ "SqlFixedString", "de/dae/classLightweight_1_1SqlFixedString.html", "de/dae/classLightweight_1_1SqlFixedString" ],
      [ "SqlForeignKeyReferenceDefinition", "d5/d8f/structLightweight_1_1SqlForeignKeyReferenceDefinition.html", "d5/d8f/structLightweight_1_1SqlForeignKeyReferenceDefinition" ],
      [ "SqlGuid", "df/d7c/structLightweight_1_1SqlGuid.html", "df/d7c/structLightweight_1_1SqlGuid" ],
      [ "SqlInsertDataPlan", "dd/d76/structLightweight_1_1SqlInsertDataPlan.html", "dd/d76/structLightweight_1_1SqlInsertDataPlan" ],
      [ "SqlInsertQueryBuilder", "de/dd9/classLightweight_1_1SqlInsertQueryBuilder.html", "de/dd9/classLightweight_1_1SqlInsertQueryBuilder" ],
      [ "SqlJoinConditionBuilder", "dd/d97/classLightweight_1_1SqlJoinConditionBuilder.html", "dd/d97/classLightweight_1_1SqlJoinConditionBuilder" ],
      [ "SqlLogger", "db/dfd/classLightweight_1_1SqlLogger.html", "db/dfd/classLightweight_1_1SqlLogger" ],
      [ "SqlMigrationDeleteBuilder", "da/d17/classLightweight_1_1SqlMigrationDeleteBuilder.html", "da/d17/classLightweight_1_1SqlMigrationDeleteBuilder" ],
      [ "SqlMigrationInsertBuilder", "d0/d05/classLightweight_1_1SqlMigrationInsertBuilder.html", "d0/d05/classLightweight_1_1SqlMigrationInsertBuilder" ],
      [ "SqlMigrationPlan", "d3/ded/structLightweight_1_1SqlMigrationPlan.html", "d3/ded/structLightweight_1_1SqlMigrationPlan" ],
      [ "SqlMigrationQueryBuilder", "d8/d65/classLightweight_1_1SqlMigrationQueryBuilder.html", "d8/d65/classLightweight_1_1SqlMigrationQueryBuilder" ],
      [ "SqlMigrationUpdateBuilder", "db/d8c/classLightweight_1_1SqlMigrationUpdateBuilder.html", "db/d8c/classLightweight_1_1SqlMigrationUpdateBuilder" ],
      [ "SqlNullType", "da/d96/structLightweight_1_1SqlNullType.html", "da/d96/structLightweight_1_1SqlNullType" ],
      [ "SqlNumeric", "d6/d1b/structLightweight_1_1SqlNumeric.html", "d6/d1b/structLightweight_1_1SqlNumeric" ],
      [ "SqlQualifiedTableColumnName", "db/d8e/structLightweight_1_1SqlQualifiedTableColumnName.html", "db/d8e/structLightweight_1_1SqlQualifiedTableColumnName" ],
      [ "SqlQueryBuilder", "de/da0/classLightweight_1_1SqlQueryBuilder.html", "de/da0/classLightweight_1_1SqlQueryBuilder" ],
      [ "SqlQueryFormatter", "d8/df7/classLightweight_1_1SqlQueryFormatter.html", "d8/df7/classLightweight_1_1SqlQueryFormatter" ],
      [ "SqlRawColumn", "da/d7e/structLightweight_1_1SqlRawColumn.html", "da/d7e/structLightweight_1_1SqlRawColumn" ],
      [ "SqlRawColumnMetadata", "da/d07/structLightweight_1_1SqlRawColumnMetadata.html", "da/d07/structLightweight_1_1SqlRawColumnMetadata" ],
      [ "SqlRawSqlPlan", "dc/d47/structLightweight_1_1SqlRawSqlPlan.html", "dc/d47/structLightweight_1_1SqlRawSqlPlan" ],
      [ "SqlRealName", "d7/d13/structLightweight_1_1SqlRealName.html", "d7/d13/structLightweight_1_1SqlRealName" ],
      [ "SqlRequireLoadedError", "da/df2/classLightweight_1_1SqlRequireLoadedError.html", "da/df2/classLightweight_1_1SqlRequireLoadedError" ],
      [ "SqlResultCursor", "d8/d63/classLightweight_1_1SqlResultCursor.html", "d8/d63/classLightweight_1_1SqlResultCursor" ],
      [ "SqlRowIterator", "d2/d8e/classLightweight_1_1SqlRowIterator.html", "d2/d8e/classLightweight_1_1SqlRowIterator" ],
      [ "SqlScopedTimeLogger", "dc/d6c/classLightweight_1_1SqlScopedTimeLogger.html", "dc/d6c/classLightweight_1_1SqlScopedTimeLogger" ],
      [ "SqlScopedTraceLogger", "df/d9c/classLightweight_1_1SqlScopedTraceLogger.html", "df/d9c/classLightweight_1_1SqlScopedTraceLogger" ],
      [ "SqlSelectQueryBuilder", "de/d33/classLightweight_1_1SqlSelectQueryBuilder.html", "de/d33/classLightweight_1_1SqlSelectQueryBuilder" ],
      [ "SqlStatement", "db/dad/classLightweight_1_1SqlStatement.html", "db/dad/classLightweight_1_1SqlStatement" ],
      [ "SqlText", "de/dfe/structLightweight_1_1SqlText.html", "de/dfe/structLightweight_1_1SqlText" ],
      [ "SqlTime", "d7/d53/structLightweight_1_1SqlTime.html", "d7/d53/structLightweight_1_1SqlTime" ],
      [ "SqlTransaction", "d0/ddc/classLightweight_1_1SqlTransaction.html", "d0/ddc/classLightweight_1_1SqlTransaction" ],
      [ "SqlTransactionException", "d5/d19/classLightweight_1_1SqlTransactionException.html", "d5/d19/classLightweight_1_1SqlTransactionException" ],
      [ "SqlUpdateDataPlan", "d4/db0/structLightweight_1_1SqlUpdateDataPlan.html", "d4/db0/structLightweight_1_1SqlUpdateDataPlan" ],
      [ "SqlVariant", "df/d3f/structLightweight_1_1SqlVariant.html", "df/d3f/structLightweight_1_1SqlVariant" ],
      [ "SqlWhereClauseBuilder", "d7/d10/classLightweight_1_1SqlWhereClauseBuilder.html", "d7/d10/classLightweight_1_1SqlWhereClauseBuilder" ],
      [ "SqlWildcardType", "d2/d74/structLightweight_1_1SqlWildcardType.html", null ],
      [ "ThreadSafeQueue", "d4/d9e/classLightweight_1_1ThreadSafeQueue.html", "d4/d9e/classLightweight_1_1ThreadSafeQueue" ],
      [ "UniqueNameBuilder", "da/d15/classLightweight_1_1UniqueNameBuilder.html", "da/d15/classLightweight_1_1UniqueNameBuilder" ]
    ] ]
];