var hierarchy =
[
    [ "Lightweight::BelongsTo<&Album::AlbumId, Lightweight::SqlRealName { \"AlbumId\" }, Light::SqlNullable::Null >", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Artist::ArtistId, Lightweight::SqlRealName { \"ArtistId\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Customer::CustomerId, Lightweight::SqlRealName { \"CustomerId\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Employee::EmployeeId, Lightweight::SqlRealName { \"SupportRepId\" }, Light::SqlNullable::Null >", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Genre::GenreId, Lightweight::SqlRealName { \"GenreId\" }, Light::SqlNullable::Null >", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Invoice::InvoiceId, Lightweight::SqlRealName { \"InvoiceId\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Mediatype::MediaTypeId, Lightweight::SqlRealName { \"MediaTypeId\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Track::TrackId, Lightweight::SqlRealName { \"TrackId\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"AlbumId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"ArtistId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"CustomerId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"EmployeeId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"GenreId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"InvoiceId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"InvoiceLineId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"MediaTypeId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"PlaylistId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"TrackId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Lightweight::SqlRealName { \"Milliseconds\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Lightweight::SqlRealName { \"Quantity\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDateTime, Lightweight::SqlRealName { \"InvoiceDate\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 160 >, Lightweight::SqlRealName { \"Title\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 20 >, Lightweight::SqlRealName { \"FirstName\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 20 >, Lightweight::SqlRealName { \"LastName\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 200 >, Lightweight::SqlRealName { \"Name\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 40 >, Lightweight::SqlRealName { \"FirstName\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 60 >, Lightweight::SqlRealName { \"Email\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlNumeric< 10, 2 >, Lightweight::SqlRealName { \"Total\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlNumeric< 10, 2 >, Lightweight::SqlRealName { \"UnitPrice\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::AliasedTableName", "d1/d0e/structLightweight_1_1AliasedTableName.html", null ],
    [ "Lightweight::BelongsTo< TheReferencedField, ColumnNameOverrideString, Nullable >", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::DataMapper", "de/d61/classLightweight_1_1DataMapper.html", null ],
    [ "Lightweight::DataMapperOptions", "d3/db2/structLightweight_1_1DataMapperOptions.html", null ],
    [ "Lightweight::Field< T, P1, P2 >", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::HasMany< OtherRecord >", "da/df4/classLightweight_1_1HasMany.html", null ],
    [ "Lightweight::HasManyThrough< ReferencedRecordT, ThroughRecordT >", "de/d73/classLightweight_1_1HasManyThrough.html", null ],
    [ "Lightweight::HasOneThrough< OtherTable, ThroughTable >", "df/d63/classLightweight_1_1HasOneThrough.html", null ],
    [ "Lightweight::SqlAlterTableCommands::AddColumnIfNotExists", "dc/dbd/structLightweight_1_1SqlAlterTableCommands_1_1AddColumnIfNotExists.html", null ],
    [ "Lightweight::SqlAlterTableCommands::DropColumnIfExists", "d1/d55/structLightweight_1_1SqlAlterTableCommands_1_1DropColumnIfExists.html", null ],
    [ "Lightweight::SqlAlterTableCommands::DropIndexIfExists", "d9/dd1/structLightweight_1_1SqlAlterTableCommands_1_1DropIndexIfExists.html", null ],
    [ "Lightweight::SqlAlterTablePlan", "dd/d75/structLightweight_1_1SqlAlterTablePlan.html", null ],
    [ "Lightweight::SqlAlterTableQueryBuilder", "d8/dad/classLightweight_1_1SqlAlterTableQueryBuilder.html", null ],
    [ "Lightweight::SqlBackup::BackupSettings", "d9/dd5/structLightweight_1_1SqlBackup_1_1BackupSettings.html", null ],
    [ "Lightweight::SqlBackup::ChunkReader", "d2/d99/structLightweight_1_1SqlBackup_1_1ChunkReader.html", null ],
    [ "Lightweight::SqlBackup::ChunkWriter", "dd/d06/structLightweight_1_1SqlBackup_1_1ChunkWriter.html", null ],
    [ "Lightweight::SqlBackup::ColumnBatch", "d1/d6f/structLightweight_1_1SqlBackup_1_1ColumnBatch.html", null ],
    [ "Lightweight::SqlBackup::Progress", "d5/db5/structLightweight_1_1SqlBackup_1_1Progress.html", null ],
    [ "Lightweight::SqlBackup::ProgressManager", "d2/d4a/structLightweight_1_1SqlBackup_1_1ProgressManager.html", [
      [ "Lightweight::SqlBackup::ErrorTrackingProgressManager", "df/da5/classLightweight_1_1SqlBackup_1_1ErrorTrackingProgressManager.html", null ]
    ] ],
    [ "Lightweight::SqlBackup::RestoreSettings", "da/d0d/structLightweight_1_1SqlBackup_1_1RestoreSettings.html", null ],
    [ "Lightweight::SqlBackup::RetrySettings", "d4/d9f/structLightweight_1_1SqlBackup_1_1RetrySettings.html", null ],
    [ "Lightweight::SqlBackup::Sha256", "d2/d43/classLightweight_1_1SqlBackup_1_1Sha256.html", null ],
    [ "Lightweight::SqlBackup::TableFilter", "d9/dfd/classLightweight_1_1SqlBackup_1_1TableFilter.html", null ],
    [ "Lightweight::SqlBackup::TableInfo", "d9/dfa/structLightweight_1_1SqlBackup_1_1TableInfo.html", null ],
    [ "Lightweight::SqlColumnDeclaration", "dd/d71/structLightweight_1_1SqlColumnDeclaration.html", null ],
    [ "Lightweight::SqlCompositeForeignKeyConstraint", "d3/d18/structLightweight_1_1SqlCompositeForeignKeyConstraint.html", null ],
    [ "Lightweight::SqlConnection", "da/da8/classLightweight_1_1SqlConnection.html", null ],
    [ "Lightweight::SqlConnectionDataSource", "d6/d8d/structLightweight_1_1SqlConnectionDataSource.html", null ],
    [ "Lightweight::SqlConnectionString", "de/d6a/structLightweight_1_1SqlConnectionString.html", null ],
    [ "Lightweight::SqlCreateIndexPlan", "dd/d2b/structLightweight_1_1SqlCreateIndexPlan.html", null ],
    [ "Lightweight::SqlCreateTableQueryBuilder", "d4/de8/classLightweight_1_1SqlCreateTableQueryBuilder.html", null ],
    [ "Lightweight::SqlDataBinderCallback", "d9/dbb/classLightweight_1_1SqlDataBinderCallback.html", [
      [ "Lightweight::SqlStatement", "db/dad/classLightweight_1_1SqlStatement.html", null ]
    ] ],
    [ "Lightweight::SqlDate", "d9/de1/structLightweight_1_1SqlDate.html", null ],
    [ "Lightweight::SqlDateTime", "d6/dfa/structLightweight_1_1SqlDateTime.html", null ],
    [ "Lightweight::SqlDeleteDataPlan", "d2/d72/structLightweight_1_1SqlDeleteDataPlan.html", null ],
    [ "Lightweight::SqlDropTablePlan", "dd/d47/structLightweight_1_1SqlDropTablePlan.html", null ],
    [ "Lightweight::SqlDynamicBinary< N >", "d6/db6/classLightweight_1_1SqlDynamicBinary.html", null ],
    [ "Lightweight::SqlDynamicString< N, T >", "d7/d9a/classLightweight_1_1SqlDynamicString.html", null ],
    [ "Lightweight::SqlErrorInfo", "d8/d5b/structLightweight_1_1SqlErrorInfo.html", null ],
    [ "Lightweight::SqlFixedString< N, T, Mode >", "de/dae/classLightweight_1_1SqlFixedString.html", null ],
    [ "Lightweight::SqlForeignKeyReferenceDefinition", "d5/d8f/structLightweight_1_1SqlForeignKeyReferenceDefinition.html", null ],
    [ "Lightweight::SqlGuid", "df/d7c/structLightweight_1_1SqlGuid.html", null ],
    [ "Lightweight::SqlInsertDataPlan", "dd/d76/structLightweight_1_1SqlInsertDataPlan.html", null ],
    [ "Lightweight::SqlInsertQueryBuilder", "de/dd9/classLightweight_1_1SqlInsertQueryBuilder.html", null ],
    [ "Lightweight::SqlJoinConditionBuilder", "dd/d97/classLightweight_1_1SqlJoinConditionBuilder.html", null ],
    [ "Lightweight::SqlLogger", "db/dfd/classLightweight_1_1SqlLogger.html", null ],
    [ "Lightweight::SqlMigration::ChecksumVerificationResult", "da/d49/structLightweight_1_1SqlMigration_1_1ChecksumVerificationResult.html", null ],
    [ "Lightweight::SqlMigration::MigrationBase", "de/dfc/classLightweight_1_1SqlMigration_1_1MigrationBase.html", [
      [ "Lightweight::SqlMigration::Migration", "d4/d32/classLightweight_1_1SqlMigration_1_1Migration.html", null ]
    ] ],
    [ "Lightweight::SqlMigration::MigrationLock", "d0/d8d/classLightweight_1_1SqlMigration_1_1MigrationLock.html", null ],
    [ "Lightweight::SqlMigration::MigrationManager", "d4/d5c/classLightweight_1_1SqlMigration_1_1MigrationManager.html", null ],
    [ "Lightweight::SqlMigration::MigrationStatus", "d8/d37/structLightweight_1_1SqlMigration_1_1MigrationStatus.html", null ],
    [ "Lightweight::SqlMigration::MigrationTimestamp", "d3/d3b/structLightweight_1_1SqlMigration_1_1MigrationTimestamp.html", null ],
    [ "Lightweight::SqlMigration::RevertResult", "d1/de7/structLightweight_1_1SqlMigration_1_1RevertResult.html", null ],
    [ "Lightweight::SqlMigrationDeleteBuilder", "da/d17/classLightweight_1_1SqlMigrationDeleteBuilder.html", null ],
    [ "Lightweight::SqlMigrationInsertBuilder", "d0/d05/classLightweight_1_1SqlMigrationInsertBuilder.html", null ],
    [ "Lightweight::SqlMigrationPlan", "d3/ded/structLightweight_1_1SqlMigrationPlan.html", null ],
    [ "Lightweight::SqlMigrationQueryBuilder", "d8/d65/classLightweight_1_1SqlMigrationQueryBuilder.html", null ],
    [ "Lightweight::SqlMigrationUpdateBuilder", "db/d8c/classLightweight_1_1SqlMigrationUpdateBuilder.html", null ],
    [ "Lightweight::SqlNullType", "da/d96/structLightweight_1_1SqlNullType.html", null ],
    [ "Lightweight::SqlNumeric< ThePrecision, TheScale >", "d6/d1b/structLightweight_1_1SqlNumeric.html", null ],
    [ "Lightweight::SqlQualifiedTableColumnName", "db/d8e/structLightweight_1_1SqlQualifiedTableColumnName.html", null ],
    [ "Lightweight::SqlQueryBuilder", "de/da0/classLightweight_1_1SqlQueryBuilder.html", null ],
    [ "Lightweight::SqlQueryFormatter", "d8/df7/classLightweight_1_1SqlQueryFormatter.html", null ],
    [ "Lightweight::SqlRawColumn", "da/d7e/structLightweight_1_1SqlRawColumn.html", null ],
    [ "Lightweight::SqlRawColumnMetadata", "da/d07/structLightweight_1_1SqlRawColumnMetadata.html", null ],
    [ "Lightweight::SqlRawSqlPlan", "dc/d47/structLightweight_1_1SqlRawSqlPlan.html", null ],
    [ "Lightweight::SqlRealName< N >", "d7/d13/structLightweight_1_1SqlRealName.html", null ],
    [ "Lightweight::SqlResultCursor", "d8/d63/classLightweight_1_1SqlResultCursor.html", null ],
    [ "Lightweight::SqlRowIterator< T >", "d2/d8e/classLightweight_1_1SqlRowIterator.html", null ],
    [ "Lightweight::SqlSchema::Column", "d2/db8/structLightweight_1_1SqlSchema_1_1Column.html", null ],
    [ "Lightweight::SqlSchema::EventHandler", "df/da2/classLightweight_1_1SqlSchema_1_1EventHandler.html", null ],
    [ "Lightweight::SqlSchema::IndexDefinition", "d6/de6/structLightweight_1_1SqlSchema_1_1IndexDefinition.html", null ],
    [ "Lightweight::SqlSchema::Table", "d3/dda/structLightweight_1_1SqlSchema_1_1Table.html", null ],
    [ "Lightweight::SqlScopedTimeLogger", "dc/d6c/classLightweight_1_1SqlScopedTimeLogger.html", null ],
    [ "Lightweight::SqlScopedTraceLogger", "df/d9c/classLightweight_1_1SqlScopedTraceLogger.html", null ],
    [ "Lightweight::SqlText", "de/dfe/structLightweight_1_1SqlText.html", null ],
    [ "Lightweight::SqlTime", "d7/d53/structLightweight_1_1SqlTime.html", null ],
    [ "Lightweight::SqlTransaction", "d0/ddc/classLightweight_1_1SqlTransaction.html", null ],
    [ "Lightweight::SqlUpdateDataPlan", "d4/db0/structLightweight_1_1SqlUpdateDataPlan.html", null ],
    [ "Lightweight::SqlVariant", "df/d3f/structLightweight_1_1SqlVariant.html", null ],
    [ "Lightweight::SqlWhereClauseBuilder< Derived >", "d7/d10/classLightweight_1_1SqlWhereClauseBuilder.html", null ],
    [ "Lightweight::SqlWildcardType", "d2/d74/structLightweight_1_1SqlWildcardType.html", null ],
    [ "Lightweight::ThreadSafeQueue< T >", "d4/d9e/classLightweight_1_1ThreadSafeQueue.html", null ],
    [ "Lightweight::UniqueNameBuilder", "da/d15/classLightweight_1_1UniqueNameBuilder.html", null ],
    [ "Lightweight::Zip::EntryInfo", "d7/d09/structLightweight_1_1Zip_1_1EntryInfo.html", null ],
    [ "Lightweight::Zip::ZipArchive", "d4/d8a/classLightweight_1_1Zip_1_1ZipArchive.html", null ],
    [ "Lightweight::Zip::ZipEntry", "d6/d46/classLightweight_1_1Zip_1_1ZipEntry.html", null ],
    [ "Lightweight::Zip::ZipError", "da/dd4/structLightweight_1_1Zip_1_1ZipError.html", null ],
    [ "Lightweight::SqlWhereClauseBuilder< SqlAllFieldsQueryBuilder< Record, QueryOptions > >", "d7/d10/classLightweight_1_1SqlWhereClauseBuilder.html", null ],
    [ "Lightweight::SqlWhereClauseBuilder< SqlDeleteQueryBuilder >", "d7/d10/classLightweight_1_1SqlWhereClauseBuilder.html", [
      [ "Lightweight::SqlDeleteQueryBuilder", "d1/d57/classLightweight_1_1SqlDeleteQueryBuilder.html", null ]
    ] ],
    [ "Lightweight::SqlWhereClauseBuilder< SqlSelectQueryBuilder >", "d7/d10/classLightweight_1_1SqlWhereClauseBuilder.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "Lightweight::SqlRequireLoadedError", "da/df2/classLightweight_1_1SqlRequireLoadedError.html", null ],
        [ "Lightweight::SqlTransactionException", "d5/d19/classLightweight_1_1SqlTransactionException.html", null ]
      ] ]
    ] ],
    [ "std::vector< uint8_t >", null, [
      [ "Lightweight::SqlBinary", "db/db6/classLightweight_1_1SqlBinary.html", null ]
    ] ]
];