var hierarchy =
[
    [ "Lightweight::BelongsTo<&Album::AlbumId, Lightweight::SqlRealName { \"AlbumId\" }, Light::SqlNullable::Null >", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Artist::ArtistId, Lightweight::SqlRealName { \"ArtistId\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Customer::CustomerId, Lightweight::SqlRealName { \"CustomerId\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Employee::EmployeeId, Lightweight::SqlRealName { \"SupportRepId\" }, Light::SqlNullable::Null >", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Genre::GenreId, Lightweight::SqlRealName { \"GenreId\" }, Light::SqlNullable::Null >", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Invoice::InvoiceId, Lightweight::SqlRealName { \"InvoiceId\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Mediatype::MediaTypeId, Lightweight::SqlRealName { \"MediaTypeId\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Patient::id, Lightweight::SqlRealName { \"patient_id\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Physician::id, Lightweight::SqlRealName { \"physician_id\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&Track::TrackId, Lightweight::SqlRealName { \"TrackId\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::BelongsTo<&User::id, Lightweight::SqlRealName { \"user_id\" }>", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::Field< bool >", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"AlbumId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"ArtistId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"CustomerId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"EmployeeId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"GenreId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"InvoiceId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"InvoiceLineId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"MediaTypeId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"PlaylistId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Light::PrimaryKey::ServerSideAutoIncrement, Lightweight::SqlRealName { \"TrackId\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Lightweight::SqlRealName { \"Milliseconds\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< int32_t, Lightweight::SqlRealName { \"Quantity\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDateTime >", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDateTime, Lightweight::SqlRealName { \"InvoiceDate\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 160 >, Lightweight::SqlRealName { \"Title\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 20 >, Lightweight::SqlRealName { \"FirstName\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 20 >, Lightweight::SqlRealName { \"LastName\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 200 >, Lightweight::SqlRealName { \"Name\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 40 >, Lightweight::SqlRealName { \"FirstName\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlDynamicString< 60 >, Lightweight::SqlRealName { \"Email\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlFixedString< 25 > >", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlFixedString< 30 > >", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlFixedString< 80 > >", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlGuid, Light::PrimaryKey::AutoAssign >", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlNumeric< 10, 2 >, Lightweight::SqlRealName { \"Total\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::Field< Lightweight::SqlNumeric< 10, 2 >, Lightweight::SqlRealName { \"UnitPrice\" }>", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::HasMany< Appointment >", "da/df4/classLightweight_1_1HasMany.html", null ],
    [ "Lightweight::HasMany< Email >", "da/df4/classLightweight_1_1HasMany.html", null ],
    [ "Lightweight::HasManyThrough< Patient, Appointment >", "de/d73/classLightweight_1_1HasManyThrough.html", null ],
    [ "Lightweight::HasManyThrough< Physician, Appointment >", "de/d73/classLightweight_1_1HasManyThrough.html", null ],
    [ "Lightweight::BelongsTo< TheReferencedField, ColumnNameOverrideString, Nullable >", "d0/df7/classLightweight_1_1BelongsTo.html", null ],
    [ "Lightweight::DataMapper", "de/d61/classLightweight_1_1DataMapper.html", null ],
    [ "Lightweight::Field< T, P1, P2 >", "d2/dd0/structLightweight_1_1Field.html", null ],
    [ "Lightweight::HasMany< OtherRecord >", "da/df4/classLightweight_1_1HasMany.html", null ],
    [ "Lightweight::HasManyThrough< ReferencedRecordT, ThroughRecordT >", "de/d73/classLightweight_1_1HasManyThrough.html", null ],
    [ "Lightweight::HasOneThrough< OtherTable, ThroughTable >", "df/d63/classLightweight_1_1HasOneThrough.html", null ],
    [ "Lightweight::SqlAlterTablePlan", "dd/d75/structLightweight_1_1SqlAlterTablePlan.html", null ],
    [ "Lightweight::SqlAlterTableQueryBuilder", "d8/dad/classLightweight_1_1SqlAlterTableQueryBuilder.html", null ],
    [ "Lightweight::SqlColumnDeclaration", "dd/d71/structLightweight_1_1SqlColumnDeclaration.html", null ],
    [ "Lightweight::SqlConnection", "da/da8/classLightweight_1_1SqlConnection.html", null ],
    [ "Lightweight::SqlConnectionDataSource", "d6/d8d/structLightweight_1_1SqlConnectionDataSource.html", null ],
    [ "Lightweight::SqlConnectionString", "de/d6a/structLightweight_1_1SqlConnectionString.html", null ],
    [ "Lightweight::SqlCoreDataMapperQueryBuilder< Record, Derived >", "da/d51/classLightweight_1_1SqlCoreDataMapperQueryBuilder.html", null ],
    [ "Lightweight::SqlCreateTableQueryBuilder", "d4/de8/classLightweight_1_1SqlCreateTableQueryBuilder.html", null ],
    [ "Lightweight::SqlDataBinderCallback", "d9/dbb/classLightweight_1_1SqlDataBinderCallback.html", [
      [ "Lightweight::SqlStatement", "db/dad/classLightweight_1_1SqlStatement.html", null ]
    ] ],
    [ "Lightweight::SqlDate", "d9/de1/structLightweight_1_1SqlDate.html", null ],
    [ "Lightweight::SqlDateTime", "d6/dfa/structLightweight_1_1SqlDateTime.html", null ],
    [ "Lightweight::SqlDeleteQueryBuilder", "d1/d57/classLightweight_1_1SqlDeleteQueryBuilder.html", null ],
    [ "Lightweight::SqlDropTablePlan", "dd/d47/structLightweight_1_1SqlDropTablePlan.html", null ],
    [ "Lightweight::SqlDynamicBinary< N >", "d6/db6/classLightweight_1_1SqlDynamicBinary.html", null ],
    [ "Lightweight::SqlDynamicString< N, T >", "d7/d9a/classLightweight_1_1SqlDynamicString.html", null ],
    [ "Lightweight::SqlErrorInfo", "d8/d5b/structLightweight_1_1SqlErrorInfo.html", null ],
    [ "Lightweight::SqlFixedString< N, T, Mode >", "de/dae/classLightweight_1_1SqlFixedString.html", null ],
    [ "Lightweight::SqlForeignKeyReferenceDefinition", "d5/d8f/structLightweight_1_1SqlForeignKeyReferenceDefinition.html", null ],
    [ "Lightweight::SqlGuid", "df/d7c/structLightweight_1_1SqlGuid.html", null ],
    [ "Lightweight::SqlInsertQueryBuilder", "de/dd9/classLightweight_1_1SqlInsertQueryBuilder.html", null ],
    [ "Lightweight::SqlLogger", "db/dfd/classLightweight_1_1SqlLogger.html", null ],
    [ "Lightweight::SqlMigrationPlan", "d3/ded/structLightweight_1_1SqlMigrationPlan.html", null ],
    [ "Lightweight::SqlMigrationQueryBuilder", "d8/d65/classLightweight_1_1SqlMigrationQueryBuilder.html", null ],
    [ "Lightweight::SqlNullType", "da/d96/structLightweight_1_1SqlNullType.html", null ],
    [ "Lightweight::SqlNumeric< ThePrecision, TheScale >", "d6/d1b/structLightweight_1_1SqlNumeric.html", null ],
    [ "Lightweight::SqlQueryBuilder", "de/da0/classLightweight_1_1SqlQueryBuilder.html", null ],
    [ "Lightweight::SqlQueryFormatter", "d8/df7/classLightweight_1_1SqlQueryFormatter.html", null ],
    [ "Lightweight::SqlRealName< N >", "d7/d13/structLightweight_1_1SqlRealName.html", null ],
    [ "Lightweight::SqlResultCursor", "d8/d63/classLightweight_1_1SqlResultCursor.html", null ],
    [ "Lightweight::SqlRowIterator< T >", "d2/d8e/classLightweight_1_1SqlRowIterator.html", null ],
    [ "Lightweight::SqlSchema::Column", "d2/db8/structLightweight_1_1SqlSchema_1_1Column.html", null ],
    [ "Lightweight::SqlSchema::EventHandler", "df/da2/classLightweight_1_1SqlSchema_1_1EventHandler.html", null ],
    [ "Lightweight::SqlSchema::Table", "d3/dda/structLightweight_1_1SqlSchema_1_1Table.html", null ],
    [ "Lightweight::SqlScopedTimeLogger", "dc/d6c/classLightweight_1_1SqlScopedTimeLogger.html", null ],
    [ "Lightweight::SqlScopedTraceLogger", "df/d9c/classLightweight_1_1SqlScopedTraceLogger.html", null ],
    [ "Lightweight::SqlSelectQueryBuilder", "de/d33/classLightweight_1_1SqlSelectQueryBuilder.html", null ],
    [ "Lightweight::SqlText", "de/dfe/structLightweight_1_1SqlText.html", null ],
    [ "Lightweight::SqlTime", "d7/d53/structLightweight_1_1SqlTime.html", null ],
    [ "Lightweight::SqlTransaction", "d0/ddc/classLightweight_1_1SqlTransaction.html", null ],
    [ "Lightweight::SqlVariant", "df/d3f/structLightweight_1_1SqlVariant.html", null ],
    [ "Lightweight::UniqueNameBuilder", "da/d15/classLightweight_1_1UniqueNameBuilder.html", null ],
    [ "Lightweight::SqlCoreDataMapperQueryBuilder< Record, SqlAllFieldsQueryBuilder< Record > >", "da/d51/classLightweight_1_1SqlCoreDataMapperQueryBuilder.html", [
      [ "Lightweight::SqlAllFieldsQueryBuilder< Record >", "d8/d5d/classLightweight_1_1SqlAllFieldsQueryBuilder.html", null ]
    ] ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "Lightweight::SqlRequireLoadedError", "da/df2/classLightweight_1_1SqlRequireLoadedError.html", null ],
        [ "Lightweight::SqlTransactionException", "d5/d19/classLightweight_1_1SqlTransactionException.html", null ]
      ] ]
    ] ],
    [ "std::vector< uint8_t >", null, [
      [ "Lightweight::SqlBinary", "db/db6/classLightweight_1_1SqlBinary.html", null ]
    ] ]
];