var NAVTREEINDEX6 =
{
"index.html":[0],
"index.html#building-with-c20-modules":[0,7],
"index.html#compile-using-c26-reflection-support":[0,6],
"index.html#foreign-keys-relation":[0,3,1],
"index.html#generate-example-for-the-existing-database":[0,5],
"index.html#high-level-api":[0,3],
"index.html#mapping-query-results-to-a-simple-struct":[0,3,2],
"index.html#mapping-query-to-multiple-struct":[0,3,3],
"index.html#namespace":[0,2],
"index.html#simple-one-record-example":[0,3,0],
"index.html#sqlite-odbc-driver-installation-on-other-operating-systems":[0,4,0],
"index.html#supported-databases":[0,1],
"index.html#supported-platforms":[0,0],
"index.html#using-sqlite-for-testing-on-windows-operating-system":[0,4],
"pages.html":[],
"topics.html":[10]
};
