var searchData=
[
  ['largedb_5factivitylog_0',['LargeDb_ActivityLog',['../d9/dcd/structLargeDb__ActivityLog.html',1,'']]],
  ['largedb_5farticle_1',['LargeDb_Article',['../dd/ded/structLargeDb__Article.html',1,'']]],
  ['largedb_5fcategory_2',['LargeDb_Category',['../d9/d78/structLargeDb__Category.html',1,'']]],
  ['largedb_5forder_3',['LargeDb_Order',['../d4/d01/structLargeDb__Order.html',1,'']]],
  ['largedb_5forderitem_4',['LargeDb_OrderItem',['../d0/dcb/structLargeDb__OrderItem.html',1,'']]],
  ['largedb_5fproduct_5',['LargeDb_Product',['../dc/d33/structLargeDb__Product.html',1,'']]],
  ['largedb_5fproductimage_6',['LargeDb_ProductImage',['../d1/d27/structLargeDb__ProductImage.html',1,'']]],
  ['largedb_5fproducttag_7',['LargeDb_ProductTag',['../d7/de2/structLargeDb__ProductTag.html',1,'']]],
  ['largedb_5freview_8',['LargeDb_Review',['../d5/daa/structLargeDb__Review.html',1,'']]],
  ['largedb_5fsystemauditlog_9',['LargeDb_SystemAuditLog',['../d0/d20/structLargeDb__SystemAuditLog.html',1,'']]],
  ['largedb_5ftag_10',['LargeDb_Tag',['../db/d6f/structLargeDb__Tag.html',1,'']]],
  ['largedb_5fuser_11',['LargeDb_User',['../d4/d09/structLargeDb__User.html',1,'']]],
  ['lasterror_12',['lasterror',['../da/da8/classLightweight_1_1SqlConnection.html#ab40ae26f82d6690050a2a6a622f7cdec',1,'Lightweight::SqlConnection::LastError()'],['../db/dad/classLightweight_1_1SqlStatement.html#a5f356550905482daeb99d1a985b93110',1,'Lightweight::SqlStatement::LastError()']]],
  ['lastinsertid_13',['lastinsertid',['../de/da0/classLightweight_1_1SqlQueryBuilder.html#ad9d7e0290e84a1b8560e32a9f37d5a1f',1,'Lightweight::SqlQueryBuilder::LastInsertId()'],['../db/dad/classLightweight_1_1SqlStatement.html#a34c08cddca600ab42f61f92c3bef7d1a',1,'Lightweight::SqlStatement::LastInsertId()']]],
  ['lastused_14',['LastUsed',['../da/da8/classLightweight_1_1SqlConnection.html#ad02b8090e26e09ac511f37aad3a277df',1,'Lightweight::SqlConnection']]],
  ['level_15',['level',['../d9/dd5/structLightweight_1_1SqlBackup_1_1BackupSettings.html#a433db0c5f6bf8d24dc11eec160e262b5',1,'Lightweight::SqlBackup::BackupSettings']]],
  ['level_20api_16',['High level API',['../index.html#high-level-api',1,'']]],
  ['level_20data_20mapping_17',['High level Data Mapping',['../d9/d80/md__2home_2runner_2work_2Lightweight_2Lightweight_2docs_2usage.html#high-level-data-mapping',1,'']]],
  ['level_20structure_18',['3.1 Top-Level Structure',['../d3/dac/md__2home_2runner_2work_2Lightweight_2Lightweight_2docs_2sql-backup-format.html#autotoc_md31-top-level-structure',1,'']]],
  ['levels_19',['5.2 Compression Levels',['../d3/dac/md__2home_2runner_2work_2Lightweight_2Lightweight_2docs_2sql-backup-format.html#autotoc_md52-compression-levels',1,'']]],
  ['lightweight_20an_20odbc_20sql_20api_20for_20c_2023_20',['Lightweight, an ODBC SQL API for C++23',['../index.html',1,'']]],
  ['lightweight_20sql_20backup_20file_20format_21',['Lightweight SQL Backup File Format',['../d3/dac/md__2home_2runner_2work_2Lightweight_2Lightweight_2docs_2sql-backup-format.html',1,'']]],
  ['lightweight_3a_3adatamapperrecord_22',['DataMapperRecord',['../de/d36/conceptLightweight_1_1DataMapperRecord.html',1,'Lightweight']]],
  ['lightweight_3a_3afieldwithstorage_23',['FieldWithStorage',['../dd/da7/conceptLightweight_1_1FieldWithStorage.html',1,'Lightweight']]],
  ['lightweight_3a_3asqlqueryobject_24',['SqlQueryObject',['../d4/da8/conceptLightweight_1_1SqlQueryObject.html',1,'Lightweight']]],
  ['loadrelations_25',['LoadRelations',['../de/d61/classLightweight_1_1DataMapper.html#a2cd193a868954406545c989fbefec702',1,'Lightweight::DataMapper']]],
  ['logic_20separate_26',['Keep Data Model and Business Logic Separate',['../d2/d10/md__2home_2runner_2work_2Lightweight_2Lightweight_2docs_2best-practices.html#keep-data-model-and-business-logic-separate',1,'']]]
];
