// SPDX-License-Identifier: Apache-2.0

#include "../SqlQuery/MigrationPlan.hpp"
#include "../SqlQueryFormatter.hpp"
#include "SqlEmitter.hpp"

#include <format>
#include <fstream>
#include <stdexcept>
#include <string>
#include <string_view>

namespace Lightweight::MigrationFold
{

namespace
{
    /// @brief Builds the file header explaining what was folded and the dialect.
    [[nodiscard]] std::string BuildHeader(FoldResult const& fold, std::string_view dialectLabel)
    {
        std::string out;
        out += "-- SPDX-License-Identifier: Apache-2.0\n";
        out += "-- Auto-generated by `dbtool fold`. DO NOT EDIT.\n";
        out += std::format("-- Dialect: {}\n", dialectLabel);
        out += std::format("-- Folded migrations: {}\n", fold.foldedMigrations.size());
        if (!fold.foldedMigrations.empty())
        {
            out += std::format("-- First migration: {}\n", fold.foldedMigrations.front().first.value);
            out += std::format("-- Last migration:  {}\n", fold.foldedMigrations.back().first.value);
        }
        out += '\n';
        return out;
    }

    /// @brief Renders one plan element, ensuring each statement ends in exactly one `;`
    /// so the file is directly executable by SQL clients. Some formatters already emit a
    /// trailing `;` on certain statements; we normalise.
    void AppendStatements(std::string& out, std::vector<std::string> const& sqls)
    {
        for (auto const& sql: sqls)
        {
            std::string_view trimmed { sql };
            while (!trimmed.empty() && (trimmed.back() == ';' || trimmed.back() == '\n' || trimmed.back() == ' '))
                trimmed.remove_suffix(1);
            out.append(trimmed);
            out += ";\n";
        }
    }

    /// @brief Builds the trailing `INSERT INTO schema_migrations ...` rows that mirror
    /// what `ApplyPendingMigrations` would have done, so the post-fold DB looks identical
    /// to a full replay. Also emits the `CREATE TABLE schema_migrations` statement that
    /// `MigrationManager::CreateMigrationHistory` would normally produce.
    [[nodiscard]] std::string BuildSchemaMigrationsSeed(SqlQueryFormatter const& formatter, FoldResult const& fold)
    {
        std::string out;
        if (fold.foldedMigrations.empty())
            return out;

        // CREATE TABLE schema_migrations — mirrors the shape created by
        // `MigrationManager::CreateMigrationHistory()` so applying the .sql against an
        // empty DB lands in the same state as a normal migration apply-all.
        out += "\n-- schema_migrations table (mirrors MigrationManager::CreateMigrationHistory).\n";
        SqlCreateTablePlan smPlan {
            .schemaName = {},
            .tableName = "schema_migrations",
            .columns = {
                SqlColumnDeclaration { .name = "version", .type = SqlColumnTypeDefinitions::Bigint {},
                                       .primaryKey = SqlPrimaryKeyType::AUTO_INCREMENT, .required = true },
                SqlColumnDeclaration { .name = "checksum", .type = SqlColumnTypeDefinitions::Varchar { 65 } },
                SqlColumnDeclaration { .name = "applied_at", .type = SqlColumnTypeDefinitions::DateTime {} },
                SqlColumnDeclaration { .name = "author", .type = SqlColumnTypeDefinitions::Varchar { 128 } },
                SqlColumnDeclaration { .name = "description", .type = SqlColumnTypeDefinitions::Varchar { 1024 } },
                SqlColumnDeclaration { .name = "execution_duration_ms", .type = SqlColumnTypeDefinitions::Bigint {} },
            },
            .foreignKeys = {},
        };
        AppendStatements(out, ::Lightweight::ToSql(formatter, smPlan));
        out += '\n';

        out += "-- Stamp every folded migration as applied (mirrors ApplyPendingMigrations).\n";
        for (auto const& [ts, title]: fold.foldedMigrations)
        {
            // Use the `Lightweight::ToSql` path so the value formatting matches the dialect's
            // string-literal rules. INSERT plan element gets us the right quoting for free.
            SqlInsertDataPlan plan {
                .schemaName = {},
                .tableName = "schema_migrations",
                .columns = {
                    { "version", SqlVariant { ts.value } },
                    { "checksum", SqlVariant {} },
                    { "applied_at", SqlVariant {} },
                    { "author", SqlVariant {} },
                    { "description", SqlVariant {} },
                    { "execution_duration_ms", SqlVariant {} },
                },
            };
            AppendStatements(out, ::Lightweight::ToSql(formatter, plan));
        }
        return out;
    }
} // namespace

void EmitSqlBaseline(FoldResult const& fold, SqlEmitOptions const& options)
{
    if (!options.formatter)
        throw std::runtime_error("EmitSqlBaseline: formatter is required");

    auto const& formatter = *options.formatter;

    std::string body;
    body += BuildHeader(fold, options.dialectLabel);

    body += "-- ============================================================\n";
    body += "-- 1. Tables\n";
    body += "-- ============================================================\n\n";
    for (auto const& key: fold.creationOrder)
    {
        auto const& state = fold.tables.at(key);
        body += std::format("-- Table: {}\n", key.table);
        SqlCreateTablePlan plan {
            .schemaName = key.schema,
            .tableName = key.table,
            .columns = state.columns,
            .foreignKeys = state.compositeForeignKeys,
            .ifNotExists = state.ifNotExists,
        };
        AppendStatements(body, ::Lightweight::ToSql(formatter, plan));
        body += '\n';
    }

    if (!fold.indexes.empty())
    {
        body += "-- ============================================================\n";
        body += "-- 2. Indexes\n";
        body += "-- ============================================================\n\n";
        for (auto const& idx: fold.indexes)
            AppendStatements(body, ::Lightweight::ToSql(formatter, idx));
        body += '\n';
    }

    if (!fold.dataSteps.empty())
    {
        body += "-- ============================================================\n";
        body += "-- 3. Data steps\n";
        body += "-- ============================================================\n\n";
        SqlMigration::MigrationTimestamp lastTs { 0 };
        for (auto const& step: fold.dataSteps)
        {
            if (step.sourceTimestamp != lastTs)
            {
                body += std::format("-- From migration {}: {}\n", step.sourceTimestamp.value, step.sourceTitle);
                lastTs = step.sourceTimestamp;
            }
            AppendStatements(body, ::Lightweight::ToSql(formatter, step.element));
        }
        body += '\n';
    }

    body += "-- ============================================================\n";
    body += "-- 4. schema_migrations seed\n";
    body += "-- ============================================================\n";
    body += BuildSchemaMigrationsSeed(formatter, fold);

    std::ofstream out(options.outputPath);
    if (!out.is_open())
        throw std::runtime_error(std::format("Failed to open output file: {}", options.outputPath.string()));
    out << body;
}

} // namespace Lightweight::MigrationFold
