// SPDX-License-Identifier: Apache-2.0

#include "SqlEmitter.hpp"

#include "../SqlQuery/MigrationPlan.hpp"
#include "../SqlQueryFormatter.hpp"

#include <format>
#include <fstream>
#include <stdexcept>
#include <string>

namespace Lightweight::MigrationFold
{

namespace
{
    /// @brief Writes the file header explaining what was folded and the dialect.
    void WriteHeader(std::ostream& out, FoldResult const& fold, std::string_view dialectLabel)
    {
        out << "-- SPDX-License-Identifier: Apache-2.0\n";
        out << "-- Auto-generated by `dbtool fold`. DO NOT EDIT.\n";
        out << "-- Dialect: " << dialectLabel << "\n";
        out << "-- Folded migrations: " << fold.foldedMigrations.size() << "\n";
        if (!fold.foldedMigrations.empty())
        {
            out << "-- First migration: " << fold.foldedMigrations.front().first.value << "\n";
            out << "-- Last migration:  " << fold.foldedMigrations.back().first.value << "\n";
        }
        out << "\n";
    }

    /// @brief Renders one plan element to the output, ensuring each statement ends
    /// in exactly one `;` so the file is directly executable by SQL clients. Some
    /// formatters already emit a trailing `;` on certain statements; we normalise.
    void WriteStatements(std::ostream& out, std::vector<std::string> const& sqls)
    {
        for (auto const& sql: sqls)
        {
            std::string_view trimmed { sql };
            while (!trimmed.empty() && (trimmed.back() == ';' || trimmed.back() == '\n' || trimmed.back() == ' '))
                trimmed.remove_suffix(1);
            out << trimmed << ";\n";
        }
    }

    /// @brief Renders the trailing `INSERT INTO schema_migrations ...` rows that mirror
    /// what `ApplyPendingMigrations` would have done, so the post-fold DB looks identical
    /// to a full replay. Also emits the `CREATE TABLE schema_migrations` statement that
    /// `MigrationManager::CreateMigrationHistory` would normally produce.
    void WriteSchemaMigrationsSeed(std::ostream& out,
                                    SqlQueryFormatter const& formatter,
                                    FoldResult const& fold)
    {
        if (fold.foldedMigrations.empty())
            return;

        // CREATE TABLE schema_migrations — mirrors the shape created by
        // `MigrationManager::CreateMigrationHistory()` so applying the .sql against an
        // empty DB lands in the same state as a normal migration apply-all.
        out << "\n-- schema_migrations table (mirrors MigrationManager::CreateMigrationHistory).\n";
        SqlCreateTablePlan smPlan {
            .schemaName = {},
            .tableName = "schema_migrations",
            .columns = {
                SqlColumnDeclaration { .name = "version", .type = SqlColumnTypeDefinitions::Bigint {},
                                       .primaryKey = SqlPrimaryKeyType::AUTO_INCREMENT, .required = true },
                SqlColumnDeclaration { .name = "checksum", .type = SqlColumnTypeDefinitions::Varchar { 65 } },
                SqlColumnDeclaration { .name = "applied_at", .type = SqlColumnTypeDefinitions::DateTime {} },
                SqlColumnDeclaration { .name = "author", .type = SqlColumnTypeDefinitions::Varchar { 128 } },
                SqlColumnDeclaration { .name = "description", .type = SqlColumnTypeDefinitions::Varchar { 1024 } },
                SqlColumnDeclaration { .name = "execution_duration_ms", .type = SqlColumnTypeDefinitions::Bigint {} },
            },
            .foreignKeys = {},
        };
        WriteStatements(out, ::Lightweight::ToSql(formatter, smPlan));
        out << "\n";

        out << "-- Stamp every folded migration as applied (mirrors ApplyPendingMigrations).\n";
        for (auto const& [ts, title]: fold.foldedMigrations)
        {
            // Use the `Lightweight::ToSql` path so the value formatting matches the dialect's
            // string-literal rules. INSERT plan element gets us the right quoting for free.
            SqlInsertDataPlan plan {
                .schemaName = {},
                .tableName = "schema_migrations",
                .columns = {
                    { "version", SqlVariant { ts.value } },
                    { "checksum", SqlVariant {} },
                    { "applied_at", SqlVariant {} },
                    { "author", SqlVariant {} },
                    { "description", SqlVariant {} },
                    { "execution_duration_ms", SqlVariant {} },
                },
            };
            auto const sqls = ::Lightweight::ToSql(formatter, plan);
            WriteStatements(out, sqls);
        }
    }
} // namespace

void EmitSqlBaseline(FoldResult const& fold, SqlEmitOptions const& options)
{
    if (!options.formatter)
        throw std::runtime_error("EmitSqlBaseline: formatter is required");

    std::ofstream out(options.outputPath);
    if (!out.is_open())
        throw std::runtime_error(std::format("Failed to open output file: {}", options.outputPath.string()));

    WriteHeader(out, fold, options.dialectLabel);

    auto const& formatter = *options.formatter;

    out << "-- ============================================================\n";
    out << "-- 1. Tables\n";
    out << "-- ============================================================\n\n";
    for (auto const& key: fold.creationOrder)
    {
        auto const& state = fold.tables.at(key);
        out << "-- Table: " << key.table << "\n";
        SqlCreateTablePlan plan {
            .schemaName = key.schema,
            .tableName = key.table,
            .columns = state.columns,
            .foreignKeys = state.compositeForeignKeys,
            .ifNotExists = state.ifNotExists,
        };
        auto const sqls = ::Lightweight::ToSql(formatter, plan);
        WriteStatements(out, sqls);
        out << "\n";
    }

    if (!fold.indexes.empty())
    {
        out << "-- ============================================================\n";
        out << "-- 2. Indexes\n";
        out << "-- ============================================================\n\n";
        for (auto const& idx: fold.indexes)
        {
            auto const sqls = ::Lightweight::ToSql(formatter, idx);
            WriteStatements(out, sqls);
        }
        out << "\n";
    }

    if (!fold.dataSteps.empty())
    {
        out << "-- ============================================================\n";
        out << "-- 3. Data steps\n";
        out << "-- ============================================================\n\n";
        SqlMigration::MigrationTimestamp lastTs { 0 };
        for (auto const& step: fold.dataSteps)
        {
            if (step.sourceTimestamp != lastTs)
            {
                out << "-- From migration " << step.sourceTimestamp.value << ": " << step.sourceTitle << "\n";
                lastTs = step.sourceTimestamp;
            }
            auto const sqls = ::Lightweight::ToSql(formatter, step.element);
            WriteStatements(out, sqls);
        }
        out << "\n";
    }

    out << "-- ============================================================\n";
    out << "-- 4. schema_migrations seed\n";
    out << "-- ============================================================\n";
    WriteSchemaMigrationsSeed(out, formatter, fold);
}

} // namespace Lightweight::MigrationFold
