Lightweight: SqlCoreDataMapperQueryBuilder< Record, Derived > Class Template Reference
SqlCoreDataMapperQueryBuilder< Record, Derived > Class Template Reference
Data Mapper
#include <DataMapper.hpp>
Inherits SqlBasicSelectQueryBuilder< Derived >.
Public Member Functions
size_t Count ()
Executes a SELECT COUNT query and returns the number of records found.
std::vector< Record > All ()
Executes a SELECT query and returns all records found.
std::optional< Record > First ()
Executes a SELECT query for the first record found and returns it.
std::vector< Record > First (size_t n)
Executes a SELECT query for the first n records found and returns them.
std::vector< Record > Range (size_t offset, size_t limit)
Executes a SELECT query for a range of records and returns them.
Protected Member Functions
LIGHTWEIGHT_FORCE_INLINE SqlCoreDataMapperQueryBuilder (SqlStatement &stmt, std::string fields) noexcept
Detailed Description
template<typename Record, typename Derived>
class SqlCoreDataMapperQueryBuilder< Record, Derived >
Main API for mapping records to C++ from the database using high level C++ syntax.
Definition at line 250 of file DataMapper.hpp.
Constructor & Destructor Documentation
SqlCoreDataMapperQueryBuilder()
template<typename Record , typename Derived > LIGHTWEIGHT_FORCE_INLINE SqlCoreDataMapperQueryBuilder< Record, Derived >::SqlCoreDataMapperQueryBuilder (SqlStatement & stmt, std::string fields) inline explicit protected noexcept
Definition at line 271 of file DataMapper.hpp.
Member Function Documentation
Count()
template<typename Record , typename Derived > size_t SqlCoreDataMapperQueryBuilder< Record, Derived >::Count () inline
Executes a SELECT COUNT query and returns the number of records found.
Definition at line 280 of file DataMapper.hpp.
References SqlStatement::ExecuteDirect(), SqlResultCursor::FetchRow(), SqlResultCursor::GetColumn(), SqlStatement::GetResultCursor(), and SqlQueryFormatter::SelectCount().
All()
template<typename Record , typename Derived > std::vector< Record > SqlCoreDataMapperQueryBuilder< Record, Derived >::All () inline
Executes a SELECT query and returns all records found.
Definition at line 294 of file DataMapper.hpp.
References SqlStatement::Connection(), SqlStatement::ExecuteDirect(), SqlStatement::GetResultCursor(), SqlQueryFormatter::SelectAll(), and SqlConnection::ServerType().
First() [1/2]
template<typename Record , typename Derived > std::optional< Record > SqlCoreDataMapperQueryBuilder< Record, Derived >::First () inline
Executes a SELECT query for the first record found and returns it.
Definition at line 310 of file DataMapper.hpp.
References SqlStatement::Connection(), SqlStatement::ExecuteDirect(), SqlStatement::GetResultCursor(), SqlQueryFormatter::SelectFirst(), and SqlConnection::ServerType().
First() [2/2]
template<typename Record , typename Derived > std::vector< Record > SqlCoreDataMapperQueryBuilder< Record, Derived >::First (size_t n) inline
Executes a SELECT query for the first n records found and returns them.
Definition at line 326 of file DataMapper.hpp.
References SqlStatement::Connection(), SqlStatement::ExecuteDirect(), SqlStatement::GetResultCursor(), SqlQueryFormatter::SelectFirst(), and SqlConnection::ServerType().
Range()
template<typename Record , typename Derived > std::vector< Record > SqlCoreDataMapperQueryBuilder< Record, Derived >::Range (size_t offset, size_t limit) inline
Executes a SELECT query for a range of records and returns them.
Definition at line 343 of file DataMapper.hpp.
References SqlStatement::Connection(), SqlStatement::ExecuteDirect(), FieldNameAt, SqlStatement::GetResultCursor(), SqlQueryFormatter::SelectRange(), and SqlConnection::ServerType().
The documentation for this class was generated from the following file:
Lightweight/DataMapper/DataMapper.hpp