Lightweight: Lightweight::SqlDateTime Struct Reference
Lightweight::SqlDateTime Struct Reference
Data Types
#include <SqlDateTime.hpp>
Public Types
using native_type = std::chrono::system_clock::time_point
using duration_type = std::chrono::system_clock::duration
Public Member Functions
constexpr SqlDateTime (SqlDateTime &&) noexcept=default
constexpr SqlDateTime & operator= (SqlDateTime &&) noexcept=default
constexpr SqlDateTime (SqlDateTime const &) noexcept=default
constexpr SqlDateTime & operator= (SqlDateTime const &other) noexcept=default
constexpr std::weak_ordering operator<=> (SqlDateTime const &other) const noexcept
constexpr bool operator== (SqlDateTime const &other) const noexcept
constexpr bool operator!= (SqlDateTime const &other) const noexcept
LIGHTWEIGHT_FORCE_INLINE constexpr SqlDateTime (std::chrono::year_month_day ymd, std::chrono::hh_mm_ss< duration_type > time) noexcept
Constructs a date and time from individual components.
LIGHTWEIGHT_FORCE_INLINE constexpr SqlDateTime (std::chrono::year year, std::chrono::month month, std::chrono::day day, std::chrono::hours hour, std::chrono::minutes minute, std::chrono::seconds second, std::chrono::nanoseconds nanosecond=std::chrono::nanoseconds(0)) noexcept
Constructs a date and time from individual components.
LIGHTWEIGHT_FORCE_INLINE constexpr SqlDateTime (std::chrono::system_clock::time_point value) noexcept
Constructs a date and time from a time point.
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::year year () const noexcept
Returns the year of this date-time object.
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::month month () const noexcept
Returns the month of this date-time object.
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::day day () const noexcept
Returns the day of this date-time object.
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::hours hour () const noexcept
Returns the hour of this date-time object.
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::minutes minute () const noexcept
Returns the minute of this date-time object.
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::seconds second () const noexcept
Returns the second of this date-time object.
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::nanoseconds nanosecond () const noexcept
Returns the nanosecond of this date-time object.
LIGHTWEIGHT_FORCE_INLINE constexpr operator native_type () const noexcept
constexpr LIGHTWEIGHT_FORCE_INLINE SqlDate Date () const noexcept
Constructs only a date from a SQL date-time structure.
constexpr LIGHTWEIGHT_FORCE_INLINE SqlTime Time () const noexcept
Constructs only a time from a SQL date-time structure.
constexpr LIGHTWEIGHT_FORCE_INLINE native_type value () const noexcept
Returns the current date and time.
LIGHTWEIGHT_FORCE_INLINE SqlDateTime & operator+= (duration_type duration) noexcept
LIGHTWEIGHT_FORCE_INLINE SqlDateTime & operator-= (duration_type duration) noexcept
Static Public Member Functions
static LIGHTWEIGHT_FORCE_INLINE SqlDateTime Now () noexcept
Returns the current date and time.
static LIGHTWEIGHT_FORCE_INLINE SqlDateTime NowUTC () noexcept
Return the current date and time in UTC.
static LIGHTWEIGHT_FORCE_INLINE SQL_TIMESTAMP_STRUCT constexpr ConvertToSqlValue (native_type value) noexcept
static LIGHTWEIGHT_FORCE_INLINE SQL_TIMESTAMP_STRUCT constexpr ConvertToSqlValue (std::chrono::year_month_day ymd, std::chrono::hh_mm_ss< duration_type > hms) noexcept
static LIGHTWEIGHT_FORCE_INLINE native_type constexpr ConvertToNative (SQL_TIMESTAMP_STRUCT const &time) noexcept
Public Attributes
SQL_TIMESTAMP_STRUCT sqlValue {}
Detailed Description
Represents a date and time to efficiently write to or read from a database.
See also
SqlDate, SqlTime
Definition at line 24 of file SqlDateTime.hpp.
Member Typedef Documentation
native_type
using Lightweight::SqlDateTime::native_type = std::chrono::system_clock::time_point
Definition at line 26 of file SqlDateTime.hpp.
duration_type
using Lightweight::SqlDateTime::duration_type = std::chrono::system_clock::duration
Definition at line 27 of file SqlDateTime.hpp.
Constructor & Destructor Documentation
SqlDateTime() [1/3]
LIGHTWEIGHT_FORCE_INLINE constexpr Lightweight::SqlDateTime::SqlDateTime (std::chrono::year_month_day ymd, std::chrono::hh_mm_ss< duration_type > time) inline constexpr noexcept
Constructs a date and time from individual components.
Definition at line 65 of file SqlDateTime.hpp.
SqlDateTime() [2/3]
LIGHTWEIGHT_FORCE_INLINE constexpr Lightweight::SqlDateTime::SqlDateTime (std::chrono::year year, std::chrono::month month, std::chrono::day day, std::chrono::hours hour, std::chrono::minutes minute, std::chrono::seconds second, std::chrono::nanoseconds nanosecond = std::chrono::nanoseconds(0)) inline constexpr noexcept
Constructs a date and time from individual components.
Definition at line 81 of file SqlDateTime.hpp.
References day(), hour(), minute(), month(), nanosecond(), second(), and year().
SqlDateTime() [3/3]
LIGHTWEIGHT_FORCE_INLINE constexpr Lightweight::SqlDateTime::SqlDateTime (std::chrono::system_clock::time_point value) inline constexpr noexcept
Constructs a date and time from a time point.
Definition at line 102 of file SqlDateTime.hpp.
References value().
Member Function Documentation
Now()
static LIGHTWEIGHT_FORCE_INLINE SqlDateTime Lightweight::SqlDateTime::Now () inline static noexcept
Returns the current date and time.
Definition at line 30 of file SqlDateTime.hpp.
NowUTC()
static LIGHTWEIGHT_FORCE_INLINE SqlDateTime Lightweight::SqlDateTime::NowUTC () inline static noexcept
Return the current date and time in UTC.
Definition at line 37 of file SqlDateTime.hpp.
operator<=>()
constexpr std::weak_ordering Lightweight::SqlDateTime::operator<=> (SqlDateTime const & other) const inline constexpr noexcept
Definition at line 50 of file SqlDateTime.hpp.
operator==()
constexpr bool Lightweight::SqlDateTime::operator== (SqlDateTime const & other) const inline constexpr noexcept
Definition at line 54 of file SqlDateTime.hpp.
operator!=()
constexpr bool Lightweight::SqlDateTime::operator!= (SqlDateTime const & other) const inline constexpr noexcept
Definition at line 59 of file SqlDateTime.hpp.
year()
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::year Lightweight::SqlDateTime::year () const inline constexpr noexcept
Returns the year of this date-time object.
Definition at line 110 of file SqlDateTime.hpp.
Referenced by Date(), and SqlDateTime().
month()
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::month Lightweight::SqlDateTime::month () const inline constexpr noexcept
Returns the month of this date-time object.
Definition at line 116 of file SqlDateTime.hpp.
Referenced by Date(), and SqlDateTime().
day()
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::day Lightweight::SqlDateTime::day () const inline constexpr noexcept
Returns the day of this date-time object.
Definition at line 122 of file SqlDateTime.hpp.
Referenced by Date(), and SqlDateTime().
hour()
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::hours Lightweight::SqlDateTime::hour () const inline constexpr noexcept
Returns the hour of this date-time object.
Definition at line 128 of file SqlDateTime.hpp.
Referenced by SqlDateTime(), and Time().
minute()
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::minutes Lightweight::SqlDateTime::minute () const inline constexpr noexcept
Returns the minute of this date-time object.
Definition at line 134 of file SqlDateTime.hpp.
Referenced by SqlDateTime(), and Time().
second()
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::seconds Lightweight::SqlDateTime::second () const inline constexpr noexcept
Returns the second of this date-time object.
Definition at line 140 of file SqlDateTime.hpp.
Referenced by SqlDateTime(), and Time().
nanosecond()
constexpr LIGHTWEIGHT_FORCE_INLINE std::chrono::nanoseconds Lightweight::SqlDateTime::nanosecond () const inline constexpr noexcept
Returns the nanosecond of this date-time object.
Definition at line 146 of file SqlDateTime.hpp.
Referenced by SqlDateTime(), and Time().
operator native_type()
LIGHTWEIGHT_FORCE_INLINE constexpr Lightweight::SqlDateTime::operator native_type () const inline constexpr noexcept
Definition at line 153 of file SqlDateTime.hpp.
Date()
constexpr LIGHTWEIGHT_FORCE_INLINE SqlDate Lightweight::SqlDateTime::Date () const inline constexpr noexcept
Constructs only a date from a SQL date-time structure.
Definition at line 159 of file SqlDateTime.hpp.
References day(), month(), and year().
Time()
constexpr LIGHTWEIGHT_FORCE_INLINE SqlTime Lightweight::SqlDateTime::Time () const inline constexpr noexcept
Constructs only a time from a SQL date-time structure.
Definition at line 165 of file SqlDateTime.hpp.
References hour(), minute(), nanosecond(), and second().
ConvertToSqlValue() [1/2]
static LIGHTWEIGHT_FORCE_INLINE SQL_TIMESTAMP_STRUCT constexpr Lightweight::SqlDateTime::ConvertToSqlValue (native_type value) inline static constexpr noexcept
Definition at line 173 of file SqlDateTime.hpp.
ConvertToSqlValue() [2/2]
static LIGHTWEIGHT_FORCE_INLINE SQL_TIMESTAMP_STRUCT constexpr Lightweight::SqlDateTime::ConvertToSqlValue (std::chrono::year_month_day ymd, std::chrono::hh_mm_ss< duration_type > hms) inline static constexpr noexcept
Definition at line 183 of file SqlDateTime.hpp.
ConvertToNative()
static LIGHTWEIGHT_FORCE_INLINE native_type constexpr Lightweight::SqlDateTime::ConvertToNative (SQL_TIMESTAMP_STRUCT const & time) inline static constexpr noexcept
Definition at line 200 of file SqlDateTime.hpp.
value()
constexpr LIGHTWEIGHT_FORCE_INLINE native_type Lightweight::SqlDateTime::value () const inline constexpr noexcept
Returns the current date and time.
Definition at line 218 of file SqlDateTime.hpp.
Referenced by SqlDateTime().
operator+=()
LIGHTWEIGHT_FORCE_INLINE SqlDateTime & Lightweight::SqlDateTime::operator+= (duration_type duration) inline noexcept
Definition at line 223 of file SqlDateTime.hpp.
operator-=()
LIGHTWEIGHT_FORCE_INLINE SqlDateTime & Lightweight::SqlDateTime::operator-= (duration_type duration) inline noexcept
Definition at line 229 of file SqlDateTime.hpp.
Member Data Documentation
sqlValue
SQL_TIMESTAMP_STRUCT Lightweight::SqlDateTime::sqlValue {}
Definition at line 245 of file SqlDateTime.hpp.
The documentation for this struct was generated from the following file:
Lightweight/DataBinder/SqlDateTime.hpp