Lightweight: Lightweight::SqlNumeric< ThePrecision, TheScale > Struct Template Reference
Lightweight::SqlNumeric< ThePrecision, TheScale > Struct Template Reference
Data Types
#include <SqlNumeric.hpp>
Public Member Functions
constexpr SqlNumeric (SqlNumeric &&) noexcept=default
constexpr SqlNumeric & operator= (SqlNumeric &&) noexcept=default
constexpr SqlNumeric (SqlNumeric const &) noexcept=default
constexpr SqlNumeric & operator= (SqlNumeric const &) noexcept=default
constexpr SqlNumeric (std::floating_point auto value) noexcept
Constructs a numeric from a floating point value.
constexpr SqlNumeric (SQL_NUMERIC_STRUCT const &value) noexcept
Constructs a numeric from a SQL_NUMERIC_STRUCT.
LIGHTWEIGHT_FORCE_INLINE constexpr void assign (std::floating_point auto value) noexcept
Assigns a value to the numeric.
LIGHTWEIGHT_FORCE_INLINE constexpr SqlNumeric & operator= (std::floating_point auto value) noexcept
Assigns a floating point value to the numeric.
constexpr LIGHTWEIGHT_FORCE_INLINE auto ToUnscaledValue () const noexcept
Converts the numeric to an unscaled integer value.
constexpr LIGHTWEIGHT_FORCE_INLINE float ToFloat () const noexcept
Converts the numeric to a floating point value.
constexpr LIGHTWEIGHT_FORCE_INLINE double ToDouble () const noexcept
Converts the numeric to a double precision floating point value.
constexpr LIGHTWEIGHT_FORCE_INLINE long double ToLongDouble () const noexcept
Converts the numeric to a long double precision floating point value.
constexpr LIGHTWEIGHT_FORCE_INLINE operator float () const noexcept
Converts the numeric to a floating point value.
constexpr LIGHTWEIGHT_FORCE_INLINE operator double () const noexcept
Converts the numeric to a double precision floating point value.
constexpr LIGHTWEIGHT_FORCE_INLINE operator long double () const noexcept
Converts the numeric to a long double precision floating point value.
LIGHTWEIGHT_FORCE_INLINE std::string ToString () const
Converts the numeric to a string.
constexpr LIGHTWEIGHT_FORCE_INLINE std::weak_ordering operator<=> (SqlNumeric const &other) const noexcept
template<std::size_t OtherPrecision, std::size_t OtherScale>
constexpr LIGHTWEIGHT_FORCE_INLINE bool operator== (SqlNumeric< OtherPrecision, OtherScale > const &other) const noexcept
Public Attributes
SQL_NUMERIC_STRUCT sqlValue {}
The value is stored as a string to avoid floating point precision issues.
Static Public Attributes
static constexpr auto ColumnType = SqlColumnTypeDefinitions::Decimal { .precision = ThePrecision, .scale = TheScale }
static constexpr auto Precision = ThePrecision
Number of total digits.
static constexpr auto Scale = TheScale
Number of digits after the decimal point.
Detailed Description
template<std::size_t ThePrecision, std::size_t TheScale>
struct Lightweight::SqlNumeric< ThePrecision, TheScale >
Represents a fixed-point number with a given precision and scale.
Precision is exactly the total number of digits in the number, including the digits after the decimal point.
Scale is the number of digits after the decimal point.
Definition at line 38 of file SqlNumeric.hpp.
Constructor & Destructor Documentation
SqlNumeric() [1/2]
template<std::size_t ThePrecision, std::size_t TheScale> constexpr Lightweight::SqlNumeric< ThePrecision, TheScale >::SqlNumeric (std::floating_point auto value) inline constexpr noexcept
Constructs a numeric from a floating point value.
Definition at line 62 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::assign().
SqlNumeric() [2/2]
template<std::size_t ThePrecision, std::size_t TheScale> constexpr Lightweight::SqlNumeric< ThePrecision, TheScale >::SqlNumeric (SQL_NUMERIC_STRUCT const & value) inline explicit constexpr noexcept
Constructs a numeric from a SQL_NUMERIC_STRUCT.
Definition at line 68 of file SqlNumeric.hpp.
Member Function Documentation
assign()
template<std::size_t ThePrecision, std::size_t TheScale> LIGHTWEIGHT_FORCE_INLINE constexpr void Lightweight::SqlNumeric< ThePrecision, TheScale >::assign (std::floating_point auto value) inline constexpr noexcept
Assigns a value to the numeric.
Definition at line 77 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::Precision, Lightweight::SqlNumeric< ThePrecision, TheScale >::Scale, and Lightweight::SqlNumeric< ThePrecision, TheScale >::sqlValue.
Referenced by Lightweight::SqlNumeric< ThePrecision, TheScale >::operator=(), and Lightweight::SqlNumeric< ThePrecision, TheScale >::SqlNumeric().
operator=()
template<std::size_t ThePrecision, std::size_t TheScale> LIGHTWEIGHT_FORCE_INLINE constexpr SqlNumeric & Lightweight::SqlNumeric< ThePrecision, TheScale >::operator= (std::floating_point auto value) inline constexpr noexcept
Assigns a floating point value to the numeric.
Definition at line 94 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::assign().
ToUnscaledValue()
template<std::size_t ThePrecision, std::size_t TheScale> constexpr LIGHTWEIGHT_FORCE_INLINE auto Lightweight::SqlNumeric< ThePrecision, TheScale >::ToUnscaledValue () const inline constexpr noexcept
Converts the numeric to an unscaled integer value.
Definition at line 101 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::sqlValue.
Referenced by Lightweight::SqlNumeric< ThePrecision, TheScale >::ToDouble(), Lightweight::SqlNumeric< ThePrecision, TheScale >::ToFloat(), and Lightweight::SqlNumeric< ThePrecision, TheScale >::ToLongDouble().
ToFloat()
template<std::size_t ThePrecision, std::size_t TheScale> constexpr LIGHTWEIGHT_FORCE_INLINE float Lightweight::SqlNumeric< ThePrecision, TheScale >::ToFloat () const inline constexpr noexcept
Converts the numeric to a floating point value.
Definition at line 112 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::Scale, and Lightweight::SqlNumeric< ThePrecision, TheScale >::ToUnscaledValue().
Referenced by Lightweight::SqlNumeric< ThePrecision, TheScale >::operator float(), and Lightweight::SqlNumeric< ThePrecision, TheScale >::ToString().
ToDouble()
template<std::size_t ThePrecision, std::size_t TheScale> constexpr LIGHTWEIGHT_FORCE_INLINE double Lightweight::SqlNumeric< ThePrecision, TheScale >::ToDouble () const inline constexpr noexcept
Converts the numeric to a double precision floating point value.
Definition at line 118 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::Scale, and Lightweight::SqlNumeric< ThePrecision, TheScale >::ToUnscaledValue().
Referenced by Lightweight::SqlNumeric< ThePrecision, TheScale >::operator double().
ToLongDouble()
template<std::size_t ThePrecision, std::size_t TheScale> constexpr LIGHTWEIGHT_FORCE_INLINE long double Lightweight::SqlNumeric< ThePrecision, TheScale >::ToLongDouble () const inline constexpr noexcept
Converts the numeric to a long double precision floating point value.
Definition at line 124 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::Scale, and Lightweight::SqlNumeric< ThePrecision, TheScale >::ToUnscaledValue().
Referenced by Lightweight::SqlNumeric< ThePrecision, TheScale >::operator long double().
operator float()
template<std::size_t ThePrecision, std::size_t TheScale> constexpr LIGHTWEIGHT_FORCE_INLINE Lightweight::SqlNumeric< ThePrecision, TheScale >::operator float () const inline explicit constexpr noexcept
Converts the numeric to a floating point value.
Definition at line 130 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::ToFloat().
operator double()
template<std::size_t ThePrecision, std::size_t TheScale> constexpr LIGHTWEIGHT_FORCE_INLINE Lightweight::SqlNumeric< ThePrecision, TheScale >::operator double () const inline explicit constexpr noexcept
Converts the numeric to a double precision floating point value.
Definition at line 136 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::ToDouble().
operator long double()
template<std::size_t ThePrecision, std::size_t TheScale> constexpr LIGHTWEIGHT_FORCE_INLINE Lightweight::SqlNumeric< ThePrecision, TheScale >::operator long double () const inline explicit constexpr noexcept
Converts the numeric to a long double precision floating point value.
Definition at line 142 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::ToLongDouble().
ToString()
template<std::size_t ThePrecision, std::size_t TheScale> LIGHTWEIGHT_FORCE_INLINE std::string Lightweight::SqlNumeric< ThePrecision, TheScale >::ToString () const inline
Converts the numeric to a string.
Definition at line 148 of file SqlNumeric.hpp.
References Lightweight::SqlNumeric< ThePrecision, TheScale >::Scale, and Lightweight::SqlNumeric< ThePrecision, TheScale >::ToFloat().
operator<=>()
template<std::size_t ThePrecision, std::size_t TheScale> constexpr LIGHTWEIGHT_FORCE_INLINE std::weak_ordering Lightweight::SqlNumeric< ThePrecision, TheScale >::operator<=> (SqlNumeric< ThePrecision, TheScale > const & other) const inline constexpr noexcept
Definition at line 153 of file SqlNumeric.hpp.
operator==()
template<std::size_t ThePrecision, std::size_t TheScale> template<std::size_t OtherPrecision, std::size_t OtherScale> constexpr LIGHTWEIGHT_FORCE_INLINE bool Lightweight::SqlNumeric< ThePrecision, TheScale >::operator== (SqlNumeric< OtherPrecision, OtherScale > const & other) const inline constexpr noexcept
Definition at line 159 of file SqlNumeric.hpp.
Member Data Documentation
ColumnType
template<std::size_t ThePrecision, std::size_t TheScale> constexpr auto Lightweight::SqlNumeric< ThePrecision, TheScale >::ColumnType = SqlColumnTypeDefinitions::Decimal { .precision = ThePrecision, .scale = TheScale } static constexpr
Definition at line 40 of file SqlNumeric.hpp.
Precision
template<std::size_t ThePrecision, std::size_t TheScale> constexpr auto Lightweight::SqlNumeric< ThePrecision, TheScale >::Precision = ThePrecision static constexpr
Number of total digits.
Definition at line 43 of file SqlNumeric.hpp.
Referenced by Lightweight::SqlNumeric< ThePrecision, TheScale >::assign().
Scale
template<std::size_t ThePrecision, std::size_t TheScale> constexpr auto Lightweight::SqlNumeric< ThePrecision, TheScale >::Scale = TheScale static constexpr
Number of digits after the decimal point.
Definition at line 46 of file SqlNumeric.hpp.
Referenced by Lightweight::SqlNumeric< ThePrecision, TheScale >::assign(), Lightweight::SqlNumeric< ThePrecision, TheScale >::ToDouble(), Lightweight::SqlNumeric< ThePrecision, TheScale >::ToFloat(), Lightweight::SqlNumeric< ThePrecision, TheScale >::ToLongDouble(), and Lightweight::SqlNumeric< ThePrecision, TheScale >::ToString().
sqlValue
template<std::size_t ThePrecision, std::size_t TheScale> SQL_NUMERIC_STRUCT Lightweight::SqlNumeric< ThePrecision, TheScale >::sqlValue {}
The value is stored as a string to avoid floating point precision issues.
Definition at line 52 of file SqlNumeric.hpp.
Referenced by Lightweight::SqlNumeric< ThePrecision, TheScale >::assign(), and Lightweight::SqlNumeric< ThePrecision, TheScale >::ToUnscaledValue().
The documentation for this struct was generated from the following file:
Lightweight/DataBinder/SqlNumeric.hpp