Lightweight: Lightweight::SqlVariant Struct Reference
Lightweight::SqlVariant Struct Reference
Data Types
Represents a value that can be any of the supported SQL data types.
#include <SqlVariant.hpp>
Public Types
using InnerType = std::variant< SqlNullType, SqlGuid, bool, int8_t, short, unsigned short, int, unsigned int, long long, unsigned long long, float, double, std::string, std::string_view, std::u16string, std::u16string_view, SqlText, SqlDate, SqlTime, SqlDateTime >
The inner type of the variant.
Public Member Functions
SqlVariant ()=default
Default construct a new SqlVariant.
SqlVariant (SqlVariant const &)=default
Copy construct a new SqlVariant from another.
SqlVariant (SqlVariant &&) noexcept=default
Move construct a new SqlVariant from another.
SqlVariant & operator= (SqlVariant const &)=default
Copy assign a new SqlVariant from another.
SqlVariant & operator= (SqlVariant &&) noexcept=default
Move assign a new SqlVariant from another.
~SqlVariant ()=default
Destructor for SqlVariant.
LIGHTWEIGHT_FORCE_INLINE SqlVariant (InnerType const &other)
Copy constructor of a SqlVariant from one of the supported types.
LIGHTWEIGHT_FORCE_INLINE SqlVariant (InnerType &&other) noexcept
Move constructor of a SqlVariant from one of the supported types.
template<std::size_t N, typename T = char, SqlFixedStringMode Mode>
constexpr LIGHTWEIGHT_FORCE_INLINE SqlVariant (SqlFixedString< N, T, Mode > const &other)
Construct a new SqlVariant from a SqlFixedString.
template<std::size_t TextSize>
constexpr LIGHTWEIGHT_FORCE_INLINE SqlVariant (char const (&text)[TextSize])
Copy constructor of a SqlVariant from a char array.
template<std::size_t TextSize>
constexpr LIGHTWEIGHT_FORCE_INLINE SqlVariant (char16_t const (&text)[TextSize])
Copy constructor of a SqlVariant from a char16_t array.
template<typename T >
LIGHTWEIGHT_FORCE_INLINE SqlVariant (std::optional< T > const &other)
Copy constructor of a SqlVariant from an optional of one of the supported types.
LIGHTWEIGHT_FORCE_INLINE SqlVariant & operator= (InnerType const &other)
Assignment operator of a SqlVariant from one of the supported types.
LIGHTWEIGHT_FORCE_INLINE SqlVariant & operator= (InnerType &&other) noexcept
Assignment operator of a SqlVariant from one of the supported types.
template<detail::HasSqlViewHelper StringViewLike>
LIGHTWEIGHT_FORCE_INLINE SqlVariant (StringViewLike const *newValue)
Construct from an string-like object that implements an SqlViewHelper<>.
template<detail::HasSqlViewHelper StringViewLike>
LIGHTWEIGHT_FORCE_INLINE SqlVariant & operator= (StringViewLike const *newValue) noexcept
Assign from an string-like object that implements an SqlViewHelper<>.
LIGHTWEIGHT_FORCE_INLINE bool IsNull () const noexcept
Check if the value is NULL.
template<typename T >
LIGHTWEIGHT_FORCE_INLINE bool Is () const noexcept
Check if the value is of the specified type.
template<typename T >
LIGHTWEIGHT_FORCE_INLINE decltype(auto) Get () noexcept
Retrieve the value as the specified type.
template<typename T >
LIGHTWEIGHT_FORCE_INLINE T ValueOr (T &&defaultValue) const noexcept
Retrieve the value as the specified type, or return the default value if the value is NULL.
LIGHTWEIGHT_FORCE_INLINE std::optional< bool > TryGetBool () const noexcept
Retrieve the bool from the variant or std::nullopt.
LIGHTWEIGHT_FORCE_INLINE std::optional< int8_t > TryGetInt8 () const noexcept
Retrieve the int8_t from the variant or std::nullopt.
LIGHTWEIGHT_FORCE_INLINE std::optional< short > TryGetShort () const noexcept
Retrieve the unsigned short from the variant or std::nullopt.
LIGHTWEIGHT_FORCE_INLINE std::optional< unsigned short > TryGetUShort () const noexcept
Retrieve the unsigned short from the variant or std::nullopt.
LIGHTWEIGHT_FORCE_INLINE std::optional< int > TryGetInt () const noexcept
Retrieve the int from the variant or std::nullopt.
LIGHTWEIGHT_FORCE_INLINE std::optional< unsigned int > TryGetUInt () const noexcept
Retrieve the unsigned int from the variant or std::nullopt.
LIGHTWEIGHT_FORCE_INLINE std::optional< long long > TryGetLongLong () const noexcept
Retrieve the long long from the variant or std::nullopt.
LIGHTWEIGHT_FORCE_INLINE std::optional< unsigned long long > TryGetULongLong () const noexcept
Retrieve the unsigned long long from the variant or std::nullopt.
std::optional< std::string_view > TryGetStringView () const noexcept
function to get string_view from SqlVariant or std::nullopt
std::optional< std::u16string_view > TryGetUtf16StringView () const noexcept
LIGHTWEIGHT_FORCE_INLINE std::optional< SqlDate > TryGetDate () const
function to get SqlDate from SqlVariant or std::nullopt
bool operator== (SqlVariant const &other) const noexcept
bool operator!= (SqlVariant const &other) const noexcept
LIGHTWEIGHT_FORCE_INLINE std::optional< SqlTime > TryGetTime () const
function to get SqlTime from SqlVariant or std::nullopt
LIGHTWEIGHT_FORCE_INLINE std::optional< SqlDateTime > TryGetDateTime () const
function to get SqlDateTime from SqlVariant or std::nullopt
LIGHTWEIGHT_FORCE_INLINE std::optional< SqlGuid > TryGetGuid () const
Retrieve the GUID from the variant or std::nullopt if the value is NULL.
LIGHTWEIGHT_API std::string ToString () const
Create string representation of the variant. Can be used for debug purposes.
Public Attributes
InnerType value
Detailed Description
Represents a value that can be any of the supported SQL data types.
Use this class with care. Always prefer native types when possible, in order to avoid any unnecessary overhead.
Definition at line 44 of file SqlVariant.hpp.
Member Typedef Documentation
InnerType
using Lightweight::SqlVariant::InnerType = std::variant<SqlNullType, SqlGuid, bool, int8_t, short, unsigned short, int, unsigned int, long long, unsigned long long, float, double, std::string, std::string_view, std::u16string, std::u16string_view, SqlText, SqlDate, SqlTime, SqlDateTime>
The inner type of the variant.
This type is a variant of all the supported SQL data types.
Definition at line 49 of file SqlVariant.hpp.
Constructor & Destructor Documentation
SqlVariant() [1/7]
LIGHTWEIGHT_FORCE_INLINE Lightweight::SqlVariant::SqlVariant (InnerType const & other) inline
Copy constructor of a SqlVariant from one of the supported types.
Definition at line 86 of file SqlVariant.hpp.
SqlVariant() [2/7]
LIGHTWEIGHT_FORCE_INLINE Lightweight::SqlVariant::SqlVariant (InnerType && other) inline noexcept
Move constructor of a SqlVariant from one of the supported types.
Definition at line 92 of file SqlVariant.hpp.
SqlVariant() [3/7]
template<std::size_t N, typename T = char, SqlFixedStringMode Mode> constexpr LIGHTWEIGHT_FORCE_INLINE Lightweight::SqlVariant::SqlVariant (SqlFixedString< N, T, Mode > const & other) inline constexpr
Construct a new SqlVariant from a SqlFixedString.
Definition at line 99 of file SqlVariant.hpp.
SqlVariant() [4/7]
template<std::size_t TextSize> constexpr LIGHTWEIGHT_FORCE_INLINE Lightweight::SqlVariant::SqlVariant (char const (&) text[TextSize]) inline constexpr
Copy constructor of a SqlVariant from a char array.
Definition at line 106 of file SqlVariant.hpp.
SqlVariant() [5/7]
template<std::size_t TextSize> constexpr LIGHTWEIGHT_FORCE_INLINE Lightweight::SqlVariant::SqlVariant (char16_t const (&) text[TextSize]) inline constexpr
Copy constructor of a SqlVariant from a char16_t array.
Definition at line 113 of file SqlVariant.hpp.
SqlVariant() [6/7]
template<typename T > LIGHTWEIGHT_FORCE_INLINE Lightweight::SqlVariant::SqlVariant (std::optional< T > const & other) inline
Copy constructor of a SqlVariant from an optional of one of the supported types.
Definition at line 120 of file SqlVariant.hpp.
SqlVariant() [7/7]
template<detail::HasSqlViewHelper StringViewLike> LIGHTWEIGHT_FORCE_INLINE Lightweight::SqlVariant::SqlVariant (StringViewLike const * newValue) inline explicit
Construct from an string-like object that implements an SqlViewHelper<>.
Definition at line 141 of file SqlVariant.hpp.
Member Function Documentation
operator=() [1/3]
LIGHTWEIGHT_FORCE_INLINE SqlVariant & Lightweight::SqlVariant::operator= (InnerType const & other) inline
Assignment operator of a SqlVariant from one of the supported types.
Definition at line 126 of file SqlVariant.hpp.
operator=() [2/3]
LIGHTWEIGHT_FORCE_INLINE SqlVariant & Lightweight::SqlVariant::operator= (InnerType && other) inline noexcept
Assignment operator of a SqlVariant from one of the supported types.
Definition at line 133 of file SqlVariant.hpp.
operator=() [3/3]
template<detail::HasSqlViewHelper StringViewLike> LIGHTWEIGHT_FORCE_INLINE SqlVariant & Lightweight::SqlVariant::operator= (StringViewLike const * newValue) inline noexcept
Assign from an string-like object that implements an SqlViewHelper<>.
Definition at line 148 of file SqlVariant.hpp.
IsNull()
LIGHTWEIGHT_FORCE_INLINE bool Lightweight::SqlVariant::IsNull () const inline noexcept
Check if the value is NULL.
Definition at line 155 of file SqlVariant.hpp.
Referenced by Get(), TryGetDate(), TryGetDateTime(), TryGetGuid(), TryGetStringView(), TryGetTime(), and ValueOr().
Is()
template<typename T > LIGHTWEIGHT_FORCE_INLINE bool Lightweight::SqlVariant::Is () const inline noexcept
Check if the value is of the specified type.
Definition at line 162 of file SqlVariant.hpp.
Get()
template<typename T > LIGHTWEIGHT_FORCE_INLINE decltype(auto) Lightweight::SqlVariant::Get () inline noexcept
Retrieve the value as the specified type.
Definition at line 169 of file SqlVariant.hpp.
References IsNull().
ValueOr()
template<typename T > LIGHTWEIGHT_FORCE_INLINE T Lightweight::SqlVariant::ValueOr (T && defaultValue) const inline noexcept
Retrieve the value as the specified type, or return the default value if the value is NULL.
Definition at line 184 of file SqlVariant.hpp.
References IsNull().
TryGetBool()
LIGHTWEIGHT_FORCE_INLINE std::optional< bool > Lightweight::SqlVariant::TryGetBool () const inline noexcept
Retrieve the bool from the variant or std::nullopt.
Definition at line 197 of file SqlVariant.hpp.
TryGetInt8()
LIGHTWEIGHT_FORCE_INLINE std::optional< int8_t > Lightweight::SqlVariant::TryGetInt8 () const inline noexcept
Retrieve the int8_t from the variant or std::nullopt.
Definition at line 199 of file SqlVariant.hpp.
TryGetShort()
LIGHTWEIGHT_FORCE_INLINE std::optional< short > Lightweight::SqlVariant::TryGetShort () const inline noexcept
Retrieve the unsigned short from the variant or std::nullopt.
Definition at line 201 of file SqlVariant.hpp.
TryGetUShort()
LIGHTWEIGHT_FORCE_INLINE std::optional< unsigned short > Lightweight::SqlVariant::TryGetUShort () const inline noexcept
Retrieve the unsigned short from the variant or std::nullopt.
Definition at line 203 of file SqlVariant.hpp.
TryGetInt()
LIGHTWEIGHT_FORCE_INLINE std::optional< int > Lightweight::SqlVariant::TryGetInt () const inline noexcept
Retrieve the int from the variant or std::nullopt.
Definition at line 205 of file SqlVariant.hpp.
TryGetUInt()
LIGHTWEIGHT_FORCE_INLINE std::optional< unsigned int > Lightweight::SqlVariant::TryGetUInt () const inline noexcept
Retrieve the unsigned int from the variant or std::nullopt.
Definition at line 207 of file SqlVariant.hpp.
TryGetLongLong()
LIGHTWEIGHT_FORCE_INLINE std::optional< long long > Lightweight::SqlVariant::TryGetLongLong () const inline noexcept
Retrieve the long long from the variant or std::nullopt.
Definition at line 209 of file SqlVariant.hpp.
TryGetULongLong()
LIGHTWEIGHT_FORCE_INLINE std::optional< unsigned long long > Lightweight::SqlVariant::TryGetULongLong () const inline noexcept
Retrieve the unsigned long long from the variant or std::nullopt.
Definition at line 211 of file SqlVariant.hpp.
TryGetStringView()
std::optional< std::string_view > Lightweight::SqlVariant::TryGetStringView () const inline noexcept
function to get string_view from SqlVariant or std::nullopt
Definition at line 232 of file SqlVariant.hpp.
References IsNull().
TryGetUtf16StringView()
std::optional< std::u16string_view > Lightweight::SqlVariant::TryGetUtf16StringView () const inline noexcept
Definition at line 247 of file SqlVariant.hpp.
TryGetDate()
LIGHTWEIGHT_FORCE_INLINE std::optional< SqlDate > Lightweight::SqlVariant::TryGetDate () const inline
function to get SqlDate from SqlVariant or std::nullopt
Definition at line 262 of file SqlVariant.hpp.
References IsNull().
operator==()
bool Lightweight::SqlVariant::operator== (SqlVariant const & other) const inline noexcept
Definition at line 280 of file SqlVariant.hpp.
operator!=()
bool Lightweight::SqlVariant::operator!= (SqlVariant const & other) const inline noexcept
Definition at line 285 of file SqlVariant.hpp.
TryGetTime()
LIGHTWEIGHT_FORCE_INLINE std::optional< SqlTime > Lightweight::SqlVariant::TryGetTime () const inline
function to get SqlTime from SqlVariant or std::nullopt
Definition at line 291 of file SqlVariant.hpp.
References IsNull().
TryGetDateTime()
LIGHTWEIGHT_FORCE_INLINE std::optional< SqlDateTime > Lightweight::SqlVariant::TryGetDateTime () const inline
function to get SqlDateTime from SqlVariant or std::nullopt
Definition at line 311 of file SqlVariant.hpp.
References IsNull().
TryGetGuid()
LIGHTWEIGHT_FORCE_INLINE std::optional< SqlGuid > Lightweight::SqlVariant::TryGetGuid () const inline
Retrieve the GUID from the variant or std::nullopt if the value is NULL.
Definition at line 323 of file SqlVariant.hpp.
References IsNull().
Member Data Documentation
value
InnerType Lightweight::SqlVariant::value
Definition at line 70 of file SqlVariant.hpp.
The documentation for this struct was generated from the following file:
Lightweight/DataBinder/SqlVariant.hpp